var listOfIonicCompounds = {
"LiNO2":"Lithium Nitrite",
"LiNO3":"Lithium Nitrate",
"LiHSO4":"Lithium Hydrogen Sulfate",
"LiOH":"Lithium Hydroxide",
"LiCN":"Lithium Cyanide",
"LiMnO4":"Lithium Permanganate",
"LiHCO3":"Lithium Hydrogen Carbonate",
"LiClO":"Lithium Hypochlorite",
"LiClO2":"Lithium Chlorite",
"LiClO3":"Lithium Chlorate",
"LiClO4":"Lithium Perchlorate",
"LiBrO3":"Lithium Bromate",
"LiIO3":"Lithium Iodate",
"LiIO4":"Lithium Periodate",
"LiC2H3O2":"Lithium Acetate",
"LiH2PO4":"Lithium Dihydrogen Phosphate",
"Li2CO3":"Lithium Carbonate",
"Li2SO3":"Lithium Sulfite",
"Li2SO4":"Lithium Sulfate",
"Li2S2O3":"Lithium Thiosulfate",
"Li2O2":"Lithium Peroxide",
"Li2CrO4":"Lithium Chromate",
"Li2Cr2O7":"Lithium Dichromate",
"Li2HPO4":"Lithium Hydrogen Phosphate",
"Li3PO4":"Lithium Phosphate",
"Li3AsO4":"Lithium Arsenate",
"Li3N":"Lithium Nitride",
"Li3P":"Lithium Phosphide",
"Li3As":"Lithium Arsenide",
"Li2O":"Lithium Oxide",
"Li2S":"Lithium Sulfide",
"Li2Se":"Lithium Selenide",
"Li2Te":"Lithium Telluride",
"LiF":"Lithium Fluoride",
"LiCl":"Lithium Chloride",
"LiBr":"Lithium Bromide",
"LiI":"Lithium Iodide",
"NaNO2":"Sodium Nitrite",
"NaNO3":"Sodium Nitrate",
"NaHSO4":"Sodium Hydrogen Sulfate",
"NaOH":"Sodium Hydroxide",
"NaCN":"Sodium Cyanide",
"NaMnO4":"Sodium Permanganate",
"NaHCO3":"Sodium Hydrogen Carbonate",
"NaClO":"Sodium Hypochlorite",
"NaClO2":"Sodium Chlorite",
"NaClO3":"Sodium Chlorate",
"NaClO4":"Sodium Perchlorate",
"NaBrO3":"Sodium Bromate",
"NaIO3":"Sodium Iodate",
"NaIO4":"Sodium Periodate",
"NaC2H3O2":"Sodium Acetate",
"NaH2PO4":"Sodium Dihydrogen Phosphate",
"Na2CO3":"Sodium Carbonate",
"Na2SO3":"Sodium Sulfite",
"Na2SO4":"Sodium Sulfate",
"Na2S2O3":"Sodium Thiosulfate",
"Na2O2":"Sodium Peroxide",
"Na2CrO4":"Sodium Chromate",
"Na2Cr2O7":"Sodium Dichromate",
"Na2HPO4":"Sodium Hydrogen Phosphate",
"Na3PO4":"Sodium Phosphate",
"Na3AsO4":"Sodium Arsenate",
"Na3N":"Sodium Nitride",
"Na3P":"Sodium Phosphide",
"Na3As":"Sodium Arsenide",
"Na2O":"Sodium Oxide",
"Na2S":"Sodium Sulfide",
"Na2Se":"Sodium Selenide",
"Na2Te":"Sodium Telluride",
"NaF":"Sodium Fluoride",
"NaCl":"Sodium Chloride",
"NaBr":"Sodium Bromide",
"NaI":"Sodium Iodide",
"KNO2":"Potassium Nitrite",
"KNO3":"Potassium Nitrate",
"KHSO4":"Potassium Hydrogen Sulfate",
"KOH":"Potassium Hydroxide",
"KCN":"Potassium Cyanide",
"KMnO4":"Potassium Permanganate",
"KHCO3":"Potassium Hydrogen Carbonate",
"KClO":"Potassium Hypochlorite",
"KClO2":"Potassium Chlorite",
"KClO3":"Potassium Chlorate",
"KClO4":"Potassium Perchlorate",
"KBrO3":"Potassium Bromate",
"KIO3":"Potassium Iodate",
"KIO4":"Potassium Periodate",
"KC2H3O2":"Potassium Acetate",
"KH2PO4":"Potassium Dihydrogen Phosphate",
"K2CO3":"Potassium Carbonate",
"K2SO3":"Potassium Sulfite",
"K2SO4":"Potassium Sulfate",
"K2S2O3":"Potassium Thiosulfate",
"K2O2":"Potassium Peroxide",
"K2CrO4":"Potassium Chromate",
"K2Cr2O7":"Potassium Dichromate",
"K2HPO4":"Potassium Hydrogen Phosphate",
"K3PO4":"Potassium Phosphate",
"K3AsO4":"Potassium Arsenate",
"K3N":"Potassium Nitride",
"K3P":"Potassium Phosphide",
"K3As":"Potassium Arsenide",
"K2O":"Potassium Oxide",
"K2S":"Potassium Sulfide",
"K2Se":"Potassium Selenide",
"K2Te":"Potassium Telluride",
"KF":"Potassium Fluoride",
"KCl":"Potassium Chloride",
"KBr":"Potassium Bromide",
"KI":"Potassium Iodide",
"RbNO2":"Rubidium Nitrite",
"RbNO3":"Rubidium Nitrate",
"RbHSO4":"Rubidium Hydrogen Sulfate",
"RbOH":"Rubidium Hydroxide",
"RbCN":"Rubidium Cyanide",
"RbMnO4":"Rubidium Permanganate",
"RbHCO3":"Rubidium Hydrogen Carbonate",
"RbClO":"Rubidium Hypochlorite",
"RbClO2":"Rubidium Chlorite",
"RbClO3":"Rubidium Chlorate",
"RbClO4":"Rubidium Perchlorate",
"RbBrO3":"Rubidium Bromate",
"RbIO3":"Rubidium Iodate",
"RbIO4":"Rubidium Periodate",
"RbC2H3O2":"Rubidium Acetate",
"RbH2PO4":"Rubidium Dihydrogen Phosphate",
"Rb2CO3":"Rubidium Carbonate",
"Rb2SO3":"Rubidium Sulfite",
"Rb2SO4":"Rubidium Sulfate",
"Rb2S2O3":"Rubidium Thiosulfate",
"Rb2O2":"Rubidium Peroxide",
"Rb2CrO4":"Rubidium Chromate",
"Rb2Cr2O7":"Rubidium Dichromate",
"Rb2HPO4":"Rubidium Hydrogen Phosphate",
"Rb3PO4":"Rubidium Phosphate",
"Rb3AsO4":"Rubidium Arsenate",
"Rb3N":"Rubidium Nitride",
"Rb3P":"Rubidium Phosphide",
"Rb3As":"Rubidium Arsenide",
"Rb2O":"Rubidium Oxide",
"Rb2S":"Rubidium Sulfide",
"Rb2Se":"Rubidium Selenide",
"Rb2Te":"Rubidium Telluride",
"RbF":"Rubidium Fluoride",
"RbCl":"Rubidium Chloride",
"RbBr":"Rubidium Bromide",
"RbI":"Rubidium Iodide",
"CsNO2":"Cesium Nitrite",
"CsNO3":"Cesium Nitrate",
"CsHSO4":"Cesium Hydrogen Sulfate",
"CsOH":"Cesium Hydroxide",
"CsCN":"Cesium Cyanide",
"CsMnO4":"Cesium Permanganate",
"CsHCO3":"Cesium Hydrogen Carbonate",
"CsClO":"Cesium Hypochlorite",
"CsClO2":"Cesium Chlorite",
"CsClO3":"Cesium Chlorate",
"CsClO4":"Cesium Perchlorate",
"CsBrO3":"Cesium Bromate",
"CsIO3":"Cesium Iodate",
"CsIO4":"Cesium Periodate",
"CsC2H3O2":"Cesium Acetate",
"CsH2PO4":"Cesium Dihydrogen Phosphate",
"Cs2CO3":"Cesium Carbonate",
"Cs2SO3":"Cesium Sulfite",
"Cs2SO4":"Cesium Sulfate",
"Cs2S2O3":"Cesium Thiosulfate",
"Cs2O2":"Cesium Peroxide",
"Cs2CrO4":"Cesium Chromate",
"Cs2Cr2O7":"Cesium Dichromate",
"Cs2HPO4":"Cesium Hydrogen Phosphate",
"Cs3PO4":"Cesium Phosphate",
"Cs3AsO4":"Cesium Arsenate",
"Cs3N":"Cesium Nitride",
"Cs3P":"Cesium Phosphide",
"Cs3As":"Cesium Arsenide",
"Cs2O":"Cesium Oxide",
"Cs2S":"Cesium Sulfide",
"Cs2Se":"Cesium Selenide",
"Cs2Te":"Cesium Telluride",
"CsF":"Cesium Fluoride",
"CsCl":"Cesium Chloride",
"CsBr":"Cesium Bromide",
"CsI":"Cesium Iodide",
"Be(NO2)2":"Beryllium Nitrite",
"Be(NO3)2":"Beryllium Nitrate",
"Be(HSO4)2":"Beryllium Hydrogen Sulfate",
"Be(OH)2":"Beryllium Hydroxide",
"Be(CN)2":"Beryllium Cyanide",
"Be(MnO4)2":"Beryllium Permanganate",
"Be(HCO3)2":"Beryllium Hydrogen Carbonate",
"Be(ClO)2":"Beryllium Hypochlorite",
"Be(ClO2)2":"Beryllium Chlorite",
"Be(ClO3)2":"Beryllium Chlorate",
"Be(ClO4)2":"Beryllium Perchlorate",
"Be(BrO3)2":"Beryllium Bromate",
"Be(IO3)2":"Beryllium Iodate",
"Be(IO4)2":"Beryllium Periodate",
"Be(C2H3O2)2":"Beryllium Acetate",
"Be(H2PO4)2":"Beryllium Dihydrogen Phosphate",
"BeCO3":"Beryllium Carbonate",
"BeSO3":"Beryllium Sulfite",
"BeSO4":"Beryllium Sulfate",
"BeS2O3":"Beryllium Thiosulfate",
"BeO2":"Beryllium Peroxide",
"BeCrO4":"Beryllium Chromate",
"BeCr2O7":"Beryllium Dichromate",
"BeHPO4":"Beryllium Hydrogen Phosphate",
"Be3(PO4)2":"Beryllium Phosphate",
"Be3(AsO4)2":"Beryllium Arsenate",
"Be3N2":"Beryllium Nitride",
"Be3P2":"Beryllium Phosphide",
"Be3As2":"Beryllium Arsenide",
"BeO":"Beryllium Oxide",
"BeS":"Beryllium Sulfide",
"BeSe":"Beryllium Selenide",
"BeTe":"Beryllium Telluride",
"BeF2":"Beryllium Fluoride",
"BeCl2":"Beryllium Chloride",
"BeBr2":"Beryllium Bromide",
"BeI2":"Beryllium Iodide",
"Mg(NO2)2":"Magnesium Nitrite",
"Mg(NO3)2":"Magnesium Nitrate",
"Mg(HSO4)2":"Magnesium Hydrogen Sulfate",
"Mg(OH)2":"Magnesium Hydroxide",
"Mg(CN)2":"Magnesium Cyanide",
"Mg(MnO4)2":"Magnesium Permanganate",
"Mg(HCO3)2":"Magnesium Hydrogen Carbonate",
"Mg(ClO)2":"Magnesium Hypochlorite",
"Mg(ClO2)2":"Magnesium Chlorite",
"Mg(ClO3)2":"Magnesium Chlorate",
"Mg(ClO4)2":"Magnesium Perchlorate",
"Mg(BrO3)2":"Magnesium Bromate",
"Mg(IO3)2":"Magnesium Iodate",
"Mg(IO4)2":"Magnesium Periodate",
"Mg(C2H3O2)2":"Magnesium Acetate",
"Mg(H2PO4)2":"Magnesium Dihydrogen Phosphate",
"MgCO3":"Magnesium Carbonate",
"MgSO3":"Magnesium Sulfite",
"MgSO4":"Magnesium Sulfate",
"MgS2O3":"Magnesium Thiosulfate",
"MgO2":"Magnesium Peroxide",
"MgCrO4":"Magnesium Chromate",
"MgCr2O7":"Magnesium Dichromate",
"MgHPO4":"Magnesium Hydrogen Phosphate",
"Mg3(PO4)2":"Magnesium Phosphate",
"Mg3(AsO4)2":"Magnesium Arsenate",
"Mg3N2":"Magnesium Nitride",
"Mg3P2":"Magnesium Phosphide",
"Mg3As2":"Magnesium Arsenide",
"MgO":"Magnesium Oxide",
"MgS":"Magnesium Sulfide",
"MgSe":"Magnesium Selenide",
"MgTe":"Magnesium Telluride",
"MgF2":"Magnesium Fluoride",
"MgCl2":"Magnesium Chloride",
"MgBr2":"Magnesium Bromide",
"MgI2":"Magnesium Iodide",
"Ca(NO2)2":"Calcium Nitrite",
"Ca(NO3)2":"Calcium Nitrate",
"Ca(HSO4)2":"Calcium Hydrogen Sulfate",
"Ca(OH)2":"Calcium Hydroxide",
"Ca(CN)2":"Calcium Cyanide",
"Ca(MnO4)2":"Calcium Permanganate",
"Ca(HCO3)2":"Calcium Hydrogen Carbonate",
"Ca(ClO)2":"Calcium Hypochlorite",
"Ca(ClO2)2":"Calcium Chlorite",
"Ca(ClO3)2":"Calcium Chlorate",
"Ca(ClO4)2":"Calcium Perchlorate",
"Ca(BrO3)2":"Calcium Bromate",
"Ca(IO3)2":"Calcium Iodate",
"Ca(IO4)2":"Calcium Periodate",
"Ca(C2H3O2)2":"Calcium Acetate",
"Ca(H2PO4)2":"Calcium Dihydrogen Phosphate",
"CaCO3":"Calcium Carbonate",
"CaSO3":"Calcium Sulfite",
"CaSO4":"Calcium Sulfate",
"CaS2O3":"Calcium Thiosulfate",
"CaO2":"Calcium Peroxide",
"CaCrO4":"Calcium Chromate",
"CaCr2O7":"Calcium Dichromate",
"CaHPO4":"Calcium Hydrogen Phosphate",
"Ca3(PO4)2":"Calcium Phosphate",
"Ca3(AsO4)2":"Calcium Arsenate",
"Ca3N2":"Calcium Nitride",
"Ca3P2":"Calcium Phosphide",
"Ca3As2":"Calcium Arsenide",
"CaO":"Calcium Oxide",
"CaS":"Calcium Sulfide",
"CaSe":"Calcium Selenide",
"CaTe":"Calcium Telluride",
"CaF2":"Calcium Fluoride",
"CaCl2":"Calcium Chloride",
"CaBr2":"Calcium Bromide",
"CaI2":"Calcium Iodide",
"Sr(NO2)2":"Strontium Nitrite",
"Sr(NO3)2":"Strontium Nitrate",
"Sr(HSO4)2":"Strontium Hydrogen Sulfate",
"Sr(OH)2":"Strontium Hydroxide",
"Sr(CN)2":"Strontium Cyanide",
"Sr(MnO4)2":"Strontium Permanganate",
"Sr(HCO3)2":"Strontium Hydrogen Carbonate",
"Sr(ClO)2":"Strontium Hypochlorite",
"Sr(ClO2)2":"Strontium Chlorite",
"Sr(ClO3)2":"Strontium Chlorate",
"Sr(ClO4)2":"Strontium Perchlorate",
"Sr(BrO3)2":"Strontium Bromate",
"Sr(IO3)2":"Strontium Iodate",
"Sr(IO4)2":"Strontium Periodate",
"Sr(C2H3O2)2":"Strontium Acetate",
"Sr(H2PO4)2":"Strontium Dihydrogen Phosphate",
"SrCO3":"Strontium Carbonate",
"SrSO3":"Strontium Sulfite",
"SrSO4":"Strontium Sulfate",
"SrS2O3":"Strontium Thiosulfate",
"SrO2":"Strontium Peroxide",
"SrCrO4":"Strontium Chromate",
"SrCr2O7":"Strontium Dichromate",
"SrHPO4":"Strontium Hydrogen Phosphate",
"Sr3(PO4)2":"Strontium Phosphate",
"Sr3(AsO4)2":"Strontium Arsenate",
"Sr3N2":"Strontium Nitride",
"Sr3P2":"Strontium Phosphide",
"Sr3As2":"Strontium Arsenide",
"SrO":"Strontium Oxide",
"SrS":"Strontium Sulfide",
"SrSe":"Strontium Selenide",
"SrTe":"Strontium Telluride",
"SrF2":"Strontium Fluoride",
"SrCl2":"Strontium Chloride",
"SrBr2":"Strontium Bromide",
"SrI2":"Strontium Iodide",
"Ba(NO2)2":"Barium Nitrite",
"Ba(NO3)2":"Barium Nitrate",
"Ba(HSO4)2":"Barium Hydrogen Sulfate",
"Ba(OH)2":"Barium Hydroxide",
"Ba(CN)2":"Barium Cyanide",
"Ba(MnO4)2":"Barium Permanganate",
"Ba(HCO3)2":"Barium Hydrogen Carbonate",
"Ba(ClO)2":"Barium Hypochlorite",
"Ba(ClO2)2":"Barium Chlorite",
"Ba(ClO3)2":"Barium Chlorate",
"Ba(ClO4)2":"Barium Perchlorate",
"Ba(BrO3)2":"Barium Bromate",
"Ba(IO3)2":"Barium Iodate",
"Ba(IO4)2":"Barium Periodate",
"Ba(C2H3O2)2":"Barium Acetate",
"Ba(H2PO4)2":"Barium Dihydrogen Phosphate",
"BaCO3":"Barium Carbonate",
"BaSO3":"Barium Sulfite",
"BaSO4":"Barium Sulfate",
"BaS2O3":"Barium Thiosulfate",
"BaO2":"Barium Peroxide",
"BaCrO4":"Barium Chromate",
"BaCr2O7":"Barium Dichromate",
"BaHPO4":"Barium Hydrogen Phosphate",
"Ba3(PO4)2":"Barium Phosphate",
"Ba3(AsO4)2":"Barium Arsenate",
"Ba3N2":"Barium Nitride",
"Ba3P2":"Barium Phosphide",
"Ba3As2":"Barium Arsenide",
"BaO":"Barium Oxide",
"BaS":"Barium Sulfide",
"BaSe":"Barium Selenide",
"BaTe":"Barium Telluride",
"BaF2":"Barium Fluoride",
"BaCl2":"Barium Chloride",
"BaBr2":"Barium Bromide",
"BaI2":"Barium Iodide",
"Sc(NO2)3":"Scandium Nitrite",
"Sc(NO3)3":"Scandium Nitrate",
"Sc(HSO4)3":"Scandium Hydrogen Sulfate",
"Sc(OH)3":"Scandium Hydroxide",
"Sc(CN)3":"Scandium Cyanide",
"Sc(MnO4)3":"Scandium Permanganate",
"Sc(HCO3)3":"Scandium Hydrogen Carbonate",
"Sc(ClO)3":"Scandium Hypochlorite",
"Sc(ClO2)3":"Scandium Chlorite",
"Sc(ClO3)3":"Scandium Chlorate",
"Sc(ClO4)3":"Scandium Perchlorate",
"Sc(BrO3)3":"Scandium Bromate",
"Sc(IO3)3":"Scandium Iodate",
"Sc(IO4)3":"Scandium Periodate",
"Sc(C2H3O2)3":"Scandium Acetate",
"Sc(H2PO4)3":"Scandium Dihydrogen Phosphate",
"Sc2(CO3)3":"Scandium Carbonate",
"Sc2(SO3)3":"Scandium Sulfite",
"Sc2(SO4)3":"Scandium Sulfate",
"Sc2(S2O3)3":"Scandium Thiosulfate",
"Sc2(O2)3":"Scandium Peroxide",
"Sc2(CrO4)3":"Scandium Chromate",
"Sc2(Cr2O7)3":"Scandium Dichromate",
"Sc2(HPO4)3":"Scandium Hydrogen Phosphate",
"ScPO4":"Scandium Phosphate",
"ScAsO4":"Scandium Arsenate",
"ScN":"Scandium Nitride",
"ScP":"Scandium Phosphide",
"ScAs":"Scandium Arsenide",
"Sc2O3":"Scandium Oxide",
"Sc2S3":"Scandium Sulfide",
"Sc2Se3":"Scandium Selenide",
"Sc2Te3":"Scandium Telluride",
"ScF3":"Scandium Fluoride",
"ScCl3":"Scandium Chloride",
"ScBr3":"Scandium Bromide",
"ScI3":"Scandium Iodide",
"Y(NO2)3":"Yttrium Nitrite",
"Y(NO3)3":"Yttrium Nitrate",
"Y(HSO4)3":"Yttrium Hydrogen Sulfate",
"Y(OH)3":"Yttrium Hydroxide",
"Y(CN)3":"Yttrium Cyanide",
"Y(MnO4)3":"Yttrium Permanganate",
"Y(HCO3)3":"Yttrium Hydrogen Carbonate",
"Y(ClO)3":"Yttrium Hypochlorite",
"Y(ClO2)3":"Yttrium Chlorite",
"Y(ClO3)3":"Yttrium Chlorate",
"Y(ClO4)3":"Yttrium Perchlorate",
"Y(BrO3)3":"Yttrium Bromate",
"Y(IO3)3":"Yttrium Iodate",
"Y(IO4)3":"Yttrium Periodate",
"Y(C2H3O2)3":"Yttrium Acetate",
"Y(H2PO4)3":"Yttrium Dihydrogen Phosphate",
"Y2(CO3)3":"Yttrium Carbonate",
"Y2(SO3)3":"Yttrium Sulfite",
"Y2(SO4)3":"Yttrium Sulfate",
"Y2(S2O3)3":"Yttrium Thiosulfate",
"Y2(O2)3":"Yttrium Peroxide",
"Y2(CrO4)3":"Yttrium Chromate",
"Y2(Cr2O7)3":"Yttrium Dichromate",
"Y2(HPO4)3":"Yttrium Hydrogen Phosphate",
"YPO4":"Yttrium Phosphate",
"YAsO4":"Yttrium Arsenate",
"YN":"Yttrium Nitride",
"YP":"Yttrium Phosphide",
"YAs":"Yttrium Arsenide",
"Y2O3":"Yttrium Oxide",
"Y2S3":"Yttrium Sulfide",
"Y2Se3":"Yttrium Selenide",
"Y2Te3":"Yttrium Telluride",
"YF3":"Yttrium Fluoride",
"YCl3":"Yttrium Chloride",
"YBr3":"Yttrium Bromide",
"YI3":"Yttrium Iodide",
"La(NO2)3":"Lanthanum Nitrite",
"La(NO3)3":"Lanthanum Nitrate",
"La(HSO4)3":"Lanthanum Hydrogen Sulfate",
"La(OH)3":"Lanthanum Hydroxide",
"La(CN)3":"Lanthanum Cyanide",
"La(MnO4)3":"Lanthanum Permanganate",
"La(HCO3)3":"Lanthanum Hydrogen Carbonate",
"La(ClO)3":"Lanthanum Hypochlorite",
"La(ClO2)3":"Lanthanum Chlorite",
"La(ClO3)3":"Lanthanum Chlorate",
"La(ClO4)3":"Lanthanum Perchlorate",
"La(BrO3)3":"Lanthanum Bromate",
"La(IO3)3":"Lanthanum Iodate",
"La(IO4)3":"Lanthanum Periodate",
"La(C2H3O2)3":"Lanthanum Acetate",
"La(H2PO4)3":"Lanthanum Dihydrogen Phosphate",
"La2(CO3)3":"Lanthanum Carbonate",
"La2(SO3)3":"Lanthanum Sulfite",
"La2(SO4)3":"Lanthanum Sulfate",
"La2(S2O3)3":"Lanthanum Thiosulfate",
"La2(O2)3":"Lanthanum Peroxide",
"La2(CrO4)3":"Lanthanum Chromate",
"La2(Cr2O7)3":"Lanthanum Dichromate",
"La2(HPO4)3":"Lanthanum Hydrogen Phosphate",
"LaPO4":"Lanthanum Phosphate",
"LaAsO4":"Lanthanum Arsenate",
"LaN":"Lanthanum Nitride",
"LaP":"Lanthanum Phosphide",
"LaAs":"Lanthanum Arsenide",
"La2O3":"Lanthanum Oxide",
"La2S3":"Lanthanum Sulfide",
"La2Se3":"Lanthanum Selenide",
"La2Te3":"Lanthanum Telluride",
"LaF3":"Lanthanum Fluoride",
"LaCl3":"Lanthanum Chloride",
"LaBr3":"Lanthanum Bromide",
"LaI3":"Lanthanum Iodide",
"Ti(NO2)2":"Titanium (II) Nitrite",
"Ti(NO3)2":"Titanium (II) Nitrate",
"Ti(HSO4)2":"Titanium (II) Hydrogen Sulfate",
"Ti(OH)2":"Titanium (II) Hydroxide",
"Ti(CN)2":"Titanium (II) Cyanide",
"Ti(MnO4)2":"Titanium (II) Permanganate",
"Ti(HCO3)2":"Titanium (II) Hydrogen Carbonate",
"Ti(ClO)2":"Titanium (II) Hypochlorite",
"Ti(ClO2)2":"Titanium (II) Chlorite",
"Ti(ClO3)2":"Titanium (II) Chlorate",
"Ti(ClO4)2":"Titanium (II) Perchlorate",
"Ti(BrO3)2":"Titanium (II) Bromate",
"Ti(IO3)2":"Titanium (II) Iodate",
"Ti(IO4)2":"Titanium (II) Periodate",
"Ti(C2H3O2)2":"Titanium (II) Acetate",
"Ti(H2PO4)2":"Titanium (II) Dihydrogen Phosphate",
"TiCO3":"Titanium (II) Carbonate",
"TiSO3":"Titanium (II) Sulfite",
"TiSO4":"Titanium (II) Sulfate",
"TiS2O3":"Titanium (II) Thiosulfate",
"TiO2":"Titanium (II) Peroxide",
"TiCrO4":"Titanium (II) Chromate",
"TiCr2O7":"Titanium (II) Dichromate",
"TiHPO4":"Titanium (II) Hydrogen Phosphate",
"Ti3(PO4)2":"Titanium (II) Phosphate",
"Ti3(AsO4)2":"Titanium (II) Arsenate",
"Ti3N2":"Titanium (II) Nitride",
"Ti3P2":"Titanium (II) Phosphide",
"Ti3As2":"Titanium (II) Arsenide",
"TiO":"Titanium (II) Oxide",
"TiS":"Titanium (II) Sulfide",
"TiSe":"Titanium (II) Selenide",
"TiTe":"Titanium (II) Telluride",
"TiF2":"Titanium (II) Fluoride",
"TiCl2":"Titanium (II) Chloride",
"TiBr2":"Titanium (II) Bromide",
"TiI2":"Titanium (II) Iodide",
"Ti(NO2)3":"Titanium (III) Nitrite",
"Ti(NO3)3":"Titanium (III) Nitrate",
"Ti(HSO4)3":"Titanium (III) Hydrogen Sulfate",
"Ti(OH)3":"Titanium (III) Hydroxide",
"Ti(CN)3":"Titanium (III) Cyanide",
"Ti(MnO4)3":"Titanium (III) Permanganate",
"Ti(HCO3)3":"Titanium (III) Hydrogen Carbonate",
"Ti(ClO)3":"Titanium (III) Hypochlorite",
"Ti(ClO2)3":"Titanium (III) Chlorite",
"Ti(ClO3)3":"Titanium (III) Chlorate",
"Ti(ClO4)3":"Titanium (III) Perchlorate",
"Ti(BrO3)3":"Titanium (III) Bromate",
"Ti(IO3)3":"Titanium (III) Iodate",
"Ti(IO4)3":"Titanium (III) Periodate",
"Ti(C2H3O2)3":"Titanium (III) Acetate",
"Ti(H2PO4)3":"Titanium (III) Dihydrogen Phosphate",
"Ti2(CO3)3":"Titanium (III) Carbonate",
"Ti2(SO3)3":"Titanium (III) Sulfite",
"Ti2(SO4)3":"Titanium (III) Sulfate",
"Ti2(S2O3)3":"Titanium (III) Thiosulfate",
"Ti2(O2)3":"Titanium (III) Peroxide",
"Ti2(CrO4)3":"Titanium (III) Chromate",
"Ti2(Cr2O7)3":"Titanium (III) Dichromate",
"Ti2(HPO4)3":"Titanium (III) Hydrogen Phosphate",
"TiPO4":"Titanium (III) Phosphate",
"TiAsO4":"Titanium (III) Arsenate",
"TiN":"Titanium (III) Nitride",
"TiP":"Titanium (III) Phosphide",
"TiAs":"Titanium (III) Arsenide",
"Ti2O3":"Titanium (III) Oxide",
"Ti2S3":"Titanium (III) Sulfide",
"Ti2Se3":"Titanium (III) Selenide",
"Ti2Te3":"Titanium (III) Telluride",
"TiF3":"Titanium (III) Fluoride",
"TiCl3":"Titanium (III) Chloride",
"TiBr3":"Titanium (III) Bromide",
"TiI3":"Titanium (III) Iodide",
"V(NO2)2":"Vanadium (II) Nitrite",
"V(NO3)2":"Vanadium (II) Nitrate",
"V(HSO4)2":"Vanadium (II) Hydrogen Sulfate",
"V(OH)2":"Vanadium (II) Hydroxide",
"V(CN)2":"Vanadium (II) Cyanide",
"V(MnO4)2":"Vanadium (II) Permanganate",
"V(HCO3)2":"Vanadium (II) Hydrogen Carbonate",
"V(ClO)2":"Vanadium (II) Hypochlorite",
"V(ClO2)2":"Vanadium (II) Chlorite",
"V(ClO3)2":"Vanadium (II) Chlorate",
"V(ClO4)2":"Vanadium (II) Perchlorate",
"V(BrO3)2":"Vanadium (II) Bromate",
"V(IO3)2":"Vanadium (II) Iodate",
"V(IO4)2":"Vanadium (II) Periodate",
"V(C2H3O2)2":"Vanadium (II) Acetate",
"V(H2PO4)2":"Vanadium (II) Dihydrogen Phosphate",
"VCO3":"Vanadium (II) Carbonate",
"VSO3":"Vanadium (II) Sulfite",
"VSO4":"Vanadium (II) Sulfate",
"VS2O3":"Vanadium (II) Thiosulfate",
"VO2":"Vanadium (II) Peroxide",
"VCrO4":"Vanadium (II) Chromate",
"VCr2O7":"Vanadium (II) Dichromate",
"VHPO4":"Vanadium (II) Hydrogen Phosphate",
"V3(PO4)2":"Vanadium (II) Phosphate",
"V3(AsO4)2":"Vanadium (II) Arsenate",
"V3N2":"Vanadium (II) Nitride",
"V3P2":"Vanadium (II) Phosphide",
"V3As2":"Vanadium (II) Arsenide",
"VO":"Vanadium (II) Oxide",
"VS":"Vanadium (II) Sulfide",
"VSe":"Vanadium (II) Selenide",
"VTe":"Vanadium (II) Telluride",
"VF2":"Vanadium (II) Fluoride",
"VCl2":"Vanadium (II) Chloride",
"VBr2":"Vanadium (II) Bromide",
"VI2":"Vanadium (II) Iodide",
"V(NO2)3":"Vanadium (III) Nitrite",
"V(NO3)3":"Vanadium (III) Nitrate",
"V(HSO4)3":"Vanadium (III) Hydrogen Sulfate",
"V(OH)3":"Vanadium (III) Hydroxide",
"V(CN)3":"Vanadium (III) Cyanide",
"V(MnO4)3":"Vanadium (III) Permanganate",
"V(HCO3)3":"Vanadium (III) Hydrogen Carbonate",
"V(ClO)3":"Vanadium (III) Hypochlorite",
"V(ClO2)3":"Vanadium (III) Chlorite",
"V(ClO3)3":"Vanadium (III) Chlorate",
"V(ClO4)3":"Vanadium (III) Perchlorate",
"V(BrO3)3":"Vanadium (III) Bromate",
"V(IO3)3":"Vanadium (III) Iodate",
"V(IO4)3":"Vanadium (III) Periodate",
"V(C2H3O2)3":"Vanadium (III) Acetate",
"V(H2PO4)3":"Vanadium (III) Dihydrogen Phosphate",
"V2(CO3)3":"Vanadium (III) Carbonate",
"V2(SO3)3":"Vanadium (III) Sulfite",
"V2(SO4)3":"Vanadium (III) Sulfate",
"V2(S2O3)3":"Vanadium (III) Thiosulfate",
"V2(O2)3":"Vanadium (III) Peroxide",
"V2(CrO4)3":"Vanadium (III) Chromate",
"V2(Cr2O7)3":"Vanadium (III) Dichromate",
"V2(HPO4)3":"Vanadium (III) Hydrogen Phosphate",
"VPO4":"Vanadium (III) Phosphate",
"VAsO4":"Vanadium (III) Arsenate",
"VN":"Vanadium (III) Nitride",
"VP":"Vanadium (III) Phosphide",
"VAs":"Vanadium (III) Arsenide",
"V2O3":"Vanadium (III) Oxide",
"V2S3":"Vanadium (III) Sulfide",
"V2Se3":"Vanadium (III) Selenide",
"V2Te3":"Vanadium (III) Telluride",
"VF3":"Vanadium (III) Fluoride",
"VCl3":"Vanadium (III) Chloride",
"VBr3":"Vanadium (III) Bromide",
"VI3":"Vanadium (III) Iodide",
"Cr(NO2)2":"Chromium (II) Nitrite",
"Cr(NO3)2":"Chromium (II) Nitrate",
"Cr(HSO4)2":"Chromium (II) Hydrogen Sulfate",
"Cr(OH)2":"Chromium (II) Hydroxide",
"Cr(CN)2":"Chromium (II) Cyanide",
"Cr(MnO4)2":"Chromium (II) Permanganate",
"Cr(HCO3)2":"Chromium (II) Hydrogen Carbonate",
"Cr(ClO)2":"Chromium (II) Hypochlorite",
"Cr(ClO2)2":"Chromium (II) Chlorite",
"Cr(ClO3)2":"Chromium (II) Chlorate",
"Cr(ClO4)2":"Chromium (II) Perchlorate",
"Cr(BrO3)2":"Chromium (II) Bromate",
"Cr(IO3)2":"Chromium (II) Iodate",
"Cr(IO4)2":"Chromium (II) Periodate",
"Cr(C2H3O2)2":"Chromium (II) Acetate",
"Cr(H2PO4)2":"Chromium (II) Dihydrogen Phosphate",
"CrCO3":"Chromium (II) Carbonate",
"CrSO3":"Chromium (II) Sulfite",
"CrSO4":"Chromium (II) Sulfate",
"CrS2O3":"Chromium (II) Thiosulfate",
"CrO2":"Chromium (II) Peroxide",
"CrCrO4":"Chromium (II) Chromate",
"CrCr2O7":"Chromium (II) Dichromate",
"CrHPO4":"Chromium (II) Hydrogen Phosphate",
"Cr3(PO4)2":"Chromium (II) Phosphate",
"Cr3(AsO4)2":"Chromium (II) Arsenate",
"Cr3N2":"Chromium (II) Nitride",
"Cr3P2":"Chromium (II) Phosphide",
"Cr3As2":"Chromium (II) Arsenide",
"CrO":"Chromium (II) Oxide",
"CrS":"Chromium (II) Sulfide",
"CrSe":"Chromium (II) Selenide",
"CrTe":"Chromium (II) Telluride",
"CrF2":"Chromium (II) Fluoride",
"CrCl2":"Chromium (II) Chloride",
"CrBr2":"Chromium (II) Bromide",
"CrI2":"Chromium (II) Iodide",
"Cr(NO2)3":"Chromium (III) Nitrite",
"Cr(NO3)3":"Chromium (III) Nitrate",
"Cr(HSO4)3":"Chromium (III) Hydrogen Sulfate",
"Cr(OH)3":"Chromium (III) Hydroxide",
"Cr(CN)3":"Chromium (III) Cyanide",
"Cr(MnO4)3":"Chromium (III) Permanganate",
"Cr(HCO3)3":"Chromium (III) Hydrogen Carbonate",
"Cr(ClO)3":"Chromium (III) Hypochlorite",
"Cr(ClO2)3":"Chromium (III) Chlorite",
"Cr(ClO3)3":"Chromium (III) Chlorate",
"Cr(ClO4)3":"Chromium (III) Perchlorate",
"Cr(BrO3)3":"Chromium (III) Bromate",
"Cr(IO3)3":"Chromium (III) Iodate",
"Cr(IO4)3":"Chromium (III) Periodate",
"Cr(C2H3O2)3":"Chromium (III) Acetate",
"Cr(H2PO4)3":"Chromium (III) Dihydrogen Phosphate",
"Cr2(CO3)3":"Chromium (III) Carbonate",
"Cr2(SO3)3":"Chromium (III) Sulfite",
"Cr2(SO4)3":"Chromium (III) Sulfate",
"Cr2(S2O3)3":"Chromium (III) Thiosulfate",
"Cr2(O2)3":"Chromium (III) Peroxide",
"Cr2(CrO4)3":"Chromium (III) Chromate",
"Cr2(Cr2O7)3":"Chromium (III) Dichromate",
"Cr2(HPO4)3":"Chromium (III) Hydrogen Phosphate",
"CrPO4":"Chromium (III) Phosphate",
"CrAsO4":"Chromium (III) Arsenate",
"CrN":"Chromium (III) Nitride",
"CrP":"Chromium (III) Phosphide",
"CrAs":"Chromium (III) Arsenide",
"Cr2O3":"Chromium (III) Oxide",
"Cr2S3":"Chromium (III) Sulfide",
"Cr2Se3":"Chromium (III) Selenide",
"Cr2Te3":"Chromium (III) Telluride",
"CrF3":"Chromium (III) Fluoride",
"CrCl3":"Chromium (III) Chloride",
"CrBr3":"Chromium (III) Bromide",
"CrI3":"Chromium (III) Iodide",
"Mn(NO2)2":"Manganese (II) Nitrite",
"Mn(NO3)2":"Manganese (II) Nitrate",
"Mn(HSO4)2":"Manganese (II) Hydrogen Sulfate",
"Mn(OH)2":"Manganese (II) Hydroxide",
"Mn(CN)2":"Manganese (II) Cyanide",
"Mn(MnO4)2":"Manganese (II) Permanganate",
"Mn(HCO3)2":"Manganese (II) Hydrogen Carbonate",
"Mn(ClO)2":"Manganese (II) Hypochlorite",
"Mn(ClO2)2":"Manganese (II) Chlorite",
"Mn(ClO3)2":"Manganese (II) Chlorate",
"Mn(ClO4)2":"Manganese (II) Perchlorate",
"Mn(BrO3)2":"Manganese (II) Bromate",
"Mn(IO3)2":"Manganese (II) Iodate",
"Mn(IO4)2":"Manganese (II) Periodate",
"Mn(C2H3O2)2":"Manganese (II) Acetate",
"Mn(H2PO4)2":"Manganese (II) Dihydrogen Phosphate",
"MnCO3":"Manganese (II) Carbonate",
"MnSO3":"Manganese (II) Sulfite",
"MnSO4":"Manganese (II) Sulfate",
"MnS2O3":"Manganese (II) Thiosulfate",
"MnO2":"Manganese (II) Peroxide",
"MnCrO4":"Manganese (II) Chromate",
"MnCr2O7":"Manganese (II) Dichromate",
"MnHPO4":"Manganese (II) Hydrogen Phosphate",
"Mn3(PO4)2":"Manganese (II) Phosphate",
"Mn3(AsO4)2":"Manganese (II) Arsenate",
"Mn3N2":"Manganese (II) Nitride",
"Mn3P2":"Manganese (II) Phosphide",
"Mn3As2":"Manganese (II) Arsenide",
"MnO":"Manganese (II) Oxide",
"MnS":"Manganese (II) Sulfide",
"MnSe":"Manganese (II) Selenide",
"MnTe":"Manganese (II) Telluride",
"MnF2":"Manganese (II) Fluoride",
"MnCl2":"Manganese (II) Chloride",
"MnBr2":"Manganese (II) Bromide",
"MnI2":"Manganese (II) Iodide",
"Mn(NO2)3":"Manganese (III) Nitrite",
"Mn(NO3)3":"Manganese (III) Nitrate",
"Mn(HSO4)3":"Manganese (III) Hydrogen Sulfate",
"Mn(OH)3":"Manganese (III) Hydroxide",
"Mn(CN)3":"Manganese (III) Cyanide",
"Mn(MnO4)3":"Manganese (III) Permanganate",
"Mn(HCO3)3":"Manganese (III) Hydrogen Carbonate",
"Mn(ClO)3":"Manganese (III) Hypochlorite",
"Mn(ClO2)3":"Manganese (III) Chlorite",
"Mn(ClO3)3":"Manganese (III) Chlorate",
"Mn(ClO4)3":"Manganese (III) Perchlorate",
"Mn(BrO3)3":"Manganese (III) Bromate",
"Mn(IO3)3":"Manganese (III) Iodate",
"Mn(IO4)3":"Manganese (III) Periodate",
"Mn(C2H3O2)3":"Manganese (III) Acetate",
"Mn(H2PO4)3":"Manganese (III) Dihydrogen Phosphate",
"Mn2(CO3)3":"Manganese (III) Carbonate",
"Mn2(SO3)3":"Manganese (III) Sulfite",
"Mn2(SO4)3":"Manganese (III) Sulfate",
"Mn2(S2O3)3":"Manganese (III) Thiosulfate",
"Mn2(O2)3":"Manganese (III) Peroxide",
"Mn2(CrO4)3":"Manganese (III) Chromate",
"Mn2(Cr2O7)3":"Manganese (III) Dichromate",
"Mn2(HPO4)3":"Manganese (III) Hydrogen Phosphate",
"MnPO4":"Manganese (III) Phosphate",
"MnAsO4":"Manganese (III) Arsenate",
"MnN":"Manganese (III) Nitride",
"MnP":"Manganese (III) Phosphide",
"MnAs":"Manganese (III) Arsenide",
"Mn2O3":"Manganese (III) Oxide",
"Mn2S3":"Manganese (III) Sulfide",
"Mn2Se3":"Manganese (III) Selenide",
"Mn2Te3":"Manganese (III) Telluride",
"MnF3":"Manganese (III) Fluoride",
"MnCl3":"Manganese (III) Chloride",
"MnBr3":"Manganese (III) Bromide",
"MnI3":"Manganese (III) Iodide",
"Tc(NO2)2":"Technetium (II) Nitrite",
"Tc(NO3)2":"Technetium (II) Nitrate",
"Tc(HSO4)2":"Technetium (II) Hydrogen Sulfate",
"Tc(OH)2":"Technetium (II) Hydroxide",
"Tc(CN)2":"Technetium (II) Cyanide",
"Tc(MnO4)2":"Technetium (II) Permanganate",
"Tc(HCO3)2":"Technetium (II) Hydrogen Carbonate",
"Tc(ClO)2":"Technetium (II) Hypochlorite",
"Tc(ClO2)2":"Technetium (II) Chlorite",
"Tc(ClO3)2":"Technetium (II) Chlorate",
"Tc(ClO4)2":"Technetium (II) Perchlorate",
"Tc(BrO3)2":"Technetium (II) Bromate",
"Tc(IO3)2":"Technetium (II) Iodate",
"Tc(IO4)2":"Technetium (II) Periodate",
"Tc(C2H3O2)2":"Technetium (II) Acetate",
"Tc(H2PO4)2":"Technetium (II) Dihydrogen Phosphate",
"TcCO3":"Technetium (II) Carbonate",
"TcSO3":"Technetium (II) Sulfite",
"TcSO4":"Technetium (II) Sulfate",
"TcS2O3":"Technetium (II) Thiosulfate",
"TcO2":"Technetium (II) Peroxide",
"TcCrO4":"Technetium (II) Chromate",
"TcCr2O7":"Technetium (II) Dichromate",
"TcHPO4":"Technetium (II) Hydrogen Phosphate",
"Tc3(PO4)2":"Technetium (II) Phosphate",
"Tc3(AsO4)2":"Technetium (II) Arsenate",
"Tc3N2":"Technetium (II) Nitride",
"Tc3P2":"Technetium (II) Phosphide",
"Tc3As2":"Technetium (II) Arsenide",
"TcO":"Technetium (II) Oxide",
"TcS":"Technetium (II) Sulfide",
"TcSe":"Technetium (II) Selenide",
"TcTe":"Technetium (II) Telluride",
"TcF2":"Technetium (II) Fluoride",
"TcCl2":"Technetium (II) Chloride",
"TcBr2":"Technetium (II) Bromide",
"TcI2":"Technetium (II) Iodide",
"Fe(NO2)2":"Iron (II) Nitrite",
"Fe(NO3)2":"Iron (II) Nitrate",
"Fe(HSO4)2":"Iron (II) Hydrogen Sulfate",
"Fe(OH)2":"Iron (II) Hydroxide",
"Fe(CN)2":"Iron (II) Cyanide",
"Fe(MnO4)2":"Iron (II) Permanganate",
"Fe(HCO3)2":"Iron (II) Hydrogen Carbonate",
"Fe(ClO)2":"Iron (II) Hypochlorite",
"Fe(ClO2)2":"Iron (II) Chlorite",
"Fe(ClO3)2":"Iron (II) Chlorate",
"Fe(ClO4)2":"Iron (II) Perchlorate",
"Fe(BrO3)2":"Iron (II) Bromate",
"Fe(IO3)2":"Iron (II) Iodate",
"Fe(IO4)2":"Iron (II) Periodate",
"Fe(C2H3O2)2":"Iron (II) Acetate",
"Fe(H2PO4)2":"Iron (II) Dihydrogen Phosphate",
"FeCO3":"Iron (II) Carbonate",
"FeSO3":"Iron (II) Sulfite",
"FeSO4":"Iron (II) Sulfate",
"FeS2O3":"Iron (II) Thiosulfate",
"FeO2":"Iron (II) Peroxide",
"FeCrO4":"Iron (II) Chromate",
"FeCr2O7":"Iron (II) Dichromate",
"FeHPO4":"Iron (II) Hydrogen Phosphate",
"Fe3(PO4)2":"Iron (II) Phosphate",
"Fe3(AsO4)2":"Iron (II) Arsenate",
"Fe3N2":"Iron (II) Nitride",
"Fe3P2":"Iron (II) Phosphide",
"Fe3As2":"Iron (II) Arsenide",
"FeO":"Iron (II) Oxide",
"FeS":"Iron (II) Sulfide",
"FeSe":"Iron (II) Selenide",
"FeTe":"Iron (II) Telluride",
"FeF2":"Iron (II) Fluoride",
"FeCl2":"Iron (II) Chloride",
"FeBr2":"Iron (II) Bromide",
"FeI2":"Iron (II) Iodide",
"Fe(NO2)3":"Iron (III) Nitrite",
"Fe(NO3)3":"Iron (III) Nitrate",
"Fe(HSO4)3":"Iron (III) Hydrogen Sulfate",
"Fe(OH)3":"Iron (III) Hydroxide",
"Fe(CN)3":"Iron (III) Cyanide",
"Fe(MnO4)3":"Iron (III) Permanganate",
"Fe(HCO3)3":"Iron (III) Hydrogen Carbonate",
"Fe(ClO)3":"Iron (III) Hypochlorite",
"Fe(ClO2)3":"Iron (III) Chlorite",
"Fe(ClO3)3":"Iron (III) Chlorate",
"Fe(ClO4)3":"Iron (III) Perchlorate",
"Fe(BrO3)3":"Iron (III) Bromate",
"Fe(IO3)3":"Iron (III) Iodate",
"Fe(IO4)3":"Iron (III) Periodate",
"Fe(C2H3O2)3":"Iron (III) Acetate",
"Fe(H2PO4)3":"Iron (III) Dihydrogen Phosphate",
"Fe2(CO3)3":"Iron (III) Carbonate",
"Fe2(SO3)3":"Iron (III) Sulfite",
"Fe2(SO4)3":"Iron (III) Sulfate",
"Fe2(S2O3)3":"Iron (III) Thiosulfate",
"Fe2(O2)3":"Iron (III) Peroxide",
"Fe2(CrO4)3":"Iron (III) Chromate",
"Fe2(Cr2O7)3":"Iron (III) Dichromate",
"Fe2(HPO4)3":"Iron (III) Hydrogen Phosphate",
"FePO4":"Iron (III) Phosphate",
"FeAsO4":"Iron (III) Arsenate",
"FeN":"Iron (III) Nitride",
"FeP":"Iron (III) Phosphide",
"FeAs":"Iron (III) Arsenide",
"Fe2O3":"Iron (III) Oxide",
"Fe2S3":"Iron (III) Sulfide",
"Fe2Se3":"Iron (III) Selenide",
"Fe2Te3":"Iron (III) Telluride",
"FeF3":"Iron (III) Fluoride",
"FeCl3":"Iron (III) Chloride",
"FeBr3":"Iron (III) Bromide",
"FeI3":"Iron (III) Iodide",
"Co(NO2)2":"Cobalt (II) Nitrite",
"Co(NO3)2":"Cobalt (II) Nitrate",
"Co(HSO4)2":"Cobalt (II) Hydrogen Sulfate",
"Co(OH)2":"Cobalt (II) Hydroxide",
"Co(CN)2":"Cobalt (II) Cyanide",
"Co(MnO4)2":"Cobalt (II) Permanganate",
"Co(HCO3)2":"Cobalt (II) Hydrogen Carbonate",
"Co(ClO)2":"Cobalt (II) Hypochlorite",
"Co(ClO2)2":"Cobalt (II) Chlorite",
"Co(ClO3)2":"Cobalt (II) Chlorate",
"Co(ClO4)2":"Cobalt (II) Perchlorate",
"Co(BrO3)2":"Cobalt (II) Bromate",
"Co(IO3)2":"Cobalt (II) Iodate",
"Co(IO4)2":"Cobalt (II) Periodate",
"Co(C2H3O2)2":"Cobalt (II) Acetate",
"Co(H2PO4)2":"Cobalt (II) Dihydrogen Phosphate",
"CoCO3":"Cobalt (II) Carbonate",
"CoSO3":"Cobalt (II) Sulfite",
"CoSO4":"Cobalt (II) Sulfate",
"CoS2O3":"Cobalt (II) Thiosulfate",
"CoO2":"Cobalt (II) Peroxide",
"CoCrO4":"Cobalt (II) Chromate",
"CoCr2O7":"Cobalt (II) Dichromate",
"CoHPO4":"Cobalt (II) Hydrogen Phosphate",
"Co3(PO4)2":"Cobalt (II) Phosphate",
"Co3(AsO4)2":"Cobalt (II) Arsenate",
"Co3N2":"Cobalt (II) Nitride",
"Co3P2":"Cobalt (II) Phosphide",
"Co3As2":"Cobalt (II) Arsenide",
"CoO":"Cobalt (II) Oxide",
"CoS":"Cobalt (II) Sulfide",
"CoSe":"Cobalt (II) Selenide",
"CoTe":"Cobalt (II) Telluride",
"CoF2":"Cobalt (II) Fluoride",
"CoCl2":"Cobalt (II) Chloride",
"CoBr2":"Cobalt (II) Bromide",
"CoI2":"Cobalt (II) Iodide",
"Co(NO2)3":"Cobalt (III) Nitrite",
"Co(NO3)3":"Cobalt (III) Nitrate",
"Co(HSO4)3":"Cobalt (III) Hydrogen Sulfate",
"Co(OH)3":"Cobalt (III) Hydroxide",
"Co(CN)3":"Cobalt (III) Cyanide",
"Co(MnO4)3":"Cobalt (III) Permanganate",
"Co(HCO3)3":"Cobalt (III) Hydrogen Carbonate",
"Co(ClO)3":"Cobalt (III) Hypochlorite",
"Co(ClO2)3":"Cobalt (III) Chlorite",
"Co(ClO3)3":"Cobalt (III) Chlorate",
"Co(ClO4)3":"Cobalt (III) Perchlorate",
"Co(BrO3)3":"Cobalt (III) Bromate",
"Co(IO3)3":"Cobalt (III) Iodate",
"Co(IO4)3":"Cobalt (III) Periodate",
"Co(C2H3O2)3":"Cobalt (III) Acetate",
"Co(H2PO4)3":"Cobalt (III) Dihydrogen Phosphate",
"Co2(CO3)3":"Cobalt (III) Carbonate",
"Co2(SO3)3":"Cobalt (III) Sulfite",
"Co2(SO4)3":"Cobalt (III) Sulfate",
"Co2(S2O3)3":"Cobalt (III) Thiosulfate",
"Co2(O2)3":"Cobalt (III) Peroxide",
"Co2(CrO4)3":"Cobalt (III) Chromate",
"Co2(Cr2O7)3":"Cobalt (III) Dichromate",
"Co2(HPO4)3":"Cobalt (III) Hydrogen Phosphate",
"CoPO4":"Cobalt (III) Phosphate",
"CoAsO4":"Cobalt (III) Arsenate",
"CoN":"Cobalt (III) Nitride",
"CoP":"Cobalt (III) Phosphide",
"CoAs":"Cobalt (III) Arsenide",
"Co2O3":"Cobalt (III) Oxide",
"Co2S3":"Cobalt (III) Sulfide",
"Co2Se3":"Cobalt (III) Selenide",
"Co2Te3":"Cobalt (III) Telluride",
"CoF3":"Cobalt (III) Fluoride",
"CoCl3":"Cobalt (III) Chloride",
"CoBr3":"Cobalt (III) Bromide",
"CoI3":"Cobalt (III) Iodide",
"Ni(NO2)2":"Nickel (II) Nitrite",
"Ni(NO3)2":"Nickel (II) Nitrate",
"Ni(HSO4)2":"Nickel (II) Hydrogen Sulfate",
"Ni(OH)2":"Nickel (II) Hydroxide",
"Ni(CN)2":"Nickel (II) Cyanide",
"Ni(MnO4)2":"Nickel (II) Permanganate",
"Ni(HCO3)2":"Nickel (II) Hydrogen Carbonate",
"Ni(ClO)2":"Nickel (II) Hypochlorite",
"Ni(ClO2)2":"Nickel (II) Chlorite",
"Ni(ClO3)2":"Nickel (II) Chlorate",
"Ni(ClO4)2":"Nickel (II) Perchlorate",
"Ni(BrO3)2":"Nickel (II) Bromate",
"Ni(IO3)2":"Nickel (II) Iodate",
"Ni(IO4)2":"Nickel (II) Periodate",
"Ni(C2H3O2)2":"Nickel (II) Acetate",
"Ni(H2PO4)2":"Nickel (II) Dihydrogen Phosphate",
"NiCO3":"Nickel (II) Carbonate",
"NiSO3":"Nickel (II) Sulfite",
"NiSO4":"Nickel (II) Sulfate",
"NiS2O3":"Nickel (II) Thiosulfate",
"NiO2":"Nickel (II) Peroxide",
"NiCrO4":"Nickel (II) Chromate",
"NiCr2O7":"Nickel (II) Dichromate",
"NiHPO4":"Nickel (II) Hydrogen Phosphate",
"Ni3(PO4)2":"Nickel (II) Phosphate",
"Ni3(AsO4)2":"Nickel (II) Arsenate",
"Ni3N2":"Nickel (II) Nitride",
"Ni3P2":"Nickel (II) Phosphide",
"Ni3As2":"Nickel (II) Arsenide",
"NiO":"Nickel (II) Oxide",
"NiS":"Nickel (II) Sulfide",
"NiSe":"Nickel (II) Selenide",
"NiTe":"Nickel (II) Telluride",
"NiF2":"Nickel (II) Fluoride",
"NiCl2":"Nickel (II) Chloride",
"NiBr2":"Nickel (II) Bromide",
"NiI2":"Nickel (II) Iodide",
"Pd(NO2)2":"Palladium (II) Nitrite",
"Pd(NO3)2":"Palladium (II) Nitrate",
"Pd(HSO4)2":"Palladium (II) Hydrogen Sulfate",
"Pd(OH)2":"Palladium (II) Hydroxide",
"Pd(CN)2":"Palladium (II) Cyanide",
"Pd(MnO4)2":"Palladium (II) Permanganate",
"Pd(HCO3)2":"Palladium (II) Hydrogen Carbonate",
"Pd(ClO)2":"Palladium (II) Hypochlorite",
"Pd(ClO2)2":"Palladium (II) Chlorite",
"Pd(ClO3)2":"Palladium (II) Chlorate",
"Pd(ClO4)2":"Palladium (II) Perchlorate",
"Pd(BrO3)2":"Palladium (II) Bromate",
"Pd(IO3)2":"Palladium (II) Iodate",
"Pd(IO4)2":"Palladium (II) Periodate",
"Pd(C2H3O2)2":"Palladium (II) Acetate",
"Pd(H2PO4)2":"Palladium (II) Dihydrogen Phosphate",
"PdCO3":"Palladium (II) Carbonate",
"PdSO3":"Palladium (II) Sulfite",
"PdSO4":"Palladium (II) Sulfate",
"PdS2O3":"Palladium (II) Thiosulfate",
"PdO2":"Palladium (II) Peroxide",
"PdCrO4":"Palladium (II) Chromate",
"PdCr2O7":"Palladium (II) Dichromate",
"PdHPO4":"Palladium (II) Hydrogen Phosphate",
"Pd3(PO4)2":"Palladium (II) Phosphate",
"Pd3(AsO4)2":"Palladium (II) Arsenate",
"Pd3N2":"Palladium (II) Nitride",
"Pd3P2":"Palladium (II) Phosphide",
"Pd3As2":"Palladium (II) Arsenide",
"PdO":"Palladium (II) Oxide",
"PdS":"Palladium (II) Sulfide",
"PdSe":"Palladium (II) Selenide",
"PdTe":"Palladium (II) Telluride",
"PdF2":"Palladium (II) Fluoride",
"PdCl2":"Palladium (II) Chloride",
"PdBr2":"Palladium (II) Bromide",
"PdI2":"Palladium (II) Iodide",
"Pt(NO2)2":"Platinum (II) Nitrite",
"Pt(NO3)2":"Platinum (II) Nitrate",
"Pt(HSO4)2":"Platinum (II) Hydrogen Sulfate",
"Pt(OH)2":"Platinum (II) Hydroxide",
"Pt(CN)2":"Platinum (II) Cyanide",
"Pt(MnO4)2":"Platinum (II) Permanganate",
"Pt(HCO3)2":"Platinum (II) Hydrogen Carbonate",
"Pt(ClO)2":"Platinum (II) Hypochlorite",
"Pt(ClO2)2":"Platinum (II) Chlorite",
"Pt(ClO3)2":"Platinum (II) Chlorate",
"Pt(ClO4)2":"Platinum (II) Perchlorate",
"Pt(BrO3)2":"Platinum (II) Bromate",
"Pt(IO3)2":"Platinum (II) Iodate",
"Pt(IO4)2":"Platinum (II) Periodate",
"Pt(C2H3O2)2":"Platinum (II) Acetate",
"Pt(H2PO4)2":"Platinum (II) Dihydrogen Phosphate",
"PtCO3":"Platinum (II) Carbonate",
"PtSO3":"Platinum (II) Sulfite",
"PtSO4":"Platinum (II) Sulfate",
"PtS2O3":"Platinum (II) Thiosulfate",
"PtO2":"Platinum (II) Peroxide",
"PtCrO4":"Platinum (II) Chromate",
"PtCr2O7":"Platinum (II) Dichromate",
"PtHPO4":"Platinum (II) Hydrogen Phosphate",
"Pt3(PO4)2":"Platinum (II) Phosphate",
"Pt3(AsO4)2":"Platinum (II) Arsenate",
"Pt3N2":"Platinum (II) Nitride",
"Pt3P2":"Platinum (II) Phosphide",
"Pt3As2":"Platinum (II) Arsenide",
"PtO":"Platinum (II) Oxide",
"PtS":"Platinum (II) Sulfide",
"PtSe":"Platinum (II) Selenide",
"PtTe":"Platinum (II) Telluride",
"PtF2":"Platinum (II) Fluoride",
"PtCl2":"Platinum (II) Chloride",
"PtBr2":"Platinum (II) Bromide",
"PtI2":"Platinum (II) Iodide",
"Pt(NO2)4":"Platinum (IV) Nitrite",
"Pt(NO3)4":"Platinum (IV) Nitrate",
"Pt(HSO4)4":"Platinum (IV) Hydrogen Sulfate",
"Pt(OH)4":"Platinum (IV) Hydroxide",
"Pt(CN)4":"Platinum (IV) Cyanide",
"Pt(MnO4)4":"Platinum (IV) Permanganate",
"Pt(HCO3)4":"Platinum (IV) Hydrogen Carbonate",
"Pt(ClO)4":"Platinum (IV) Hypochlorite",
"Pt(ClO2)4":"Platinum (IV) Chlorite",
"Pt(ClO3)4":"Platinum (IV) Chlorate",
"Pt(ClO4)4":"Platinum (IV) Perchlorate",
"Pt(BrO3)4":"Platinum (IV) Bromate",
"Pt(IO3)4":"Platinum (IV) Iodate",
"Pt(IO4)4":"Platinum (IV) Periodate",
"Pt(C2H3O2)4":"Platinum (IV) Acetate",
"Pt(H2PO4)4":"Platinum (IV) Dihydrogen Phosphate",
"Pt(CO3)2":"Platinum (IV) Carbonate",
"Pt(SO3)2":"Platinum (IV) Sulfite",
"Pt(SO4)2":"Platinum (IV) Sulfate",
"Pt(S2O3)2":"Platinum (IV) Thiosulfate",
"Pt(O2)2":"Platinum (IV) Peroxide",
"Pt(CrO4)2":"Platinum (IV) Chromate",
"Pt(Cr2O7)2":"Platinum (IV) Dichromate",
"Pt(HPO4)2":"Platinum (IV) Hydrogen Phosphate",
"Pt3(PO4)4":"Platinum (IV) Phosphate",
"Pt3(AsO4)4":"Platinum (IV) Arsenate",
"Pt3N4":"Platinum (IV) Nitride",
"Pt3P4":"Platinum (IV) Phosphide",
"Pt3As4":"Platinum (IV) Arsenide",
"PtO2":"Platinum (IV) Oxide",
"PtS2":"Platinum (IV) Sulfide",
"PtSe2":"Platinum (IV) Selenide",
"PtTe2":"Platinum (IV) Telluride",
"PtF4":"Platinum (IV) Fluoride",
"PtCl4":"Platinum (IV) Chloride",
"PtBr4":"Platinum (IV) Bromide",
"PtI4":"Platinum (IV) Iodide",
"CuNO2":"Copper (I) Nitrite",
"CuNO3":"Copper (I) Nitrate",
"CuHSO4":"Copper (I) Hydrogen Sulfate",
"CuOH":"Copper (I) Hydroxide",
"CuCN":"Copper (I) Cyanide",
"CuMnO4":"Copper (I) Permanganate",
"CuHCO3":"Copper (I) Hydrogen Carbonate",
"CuClO":"Copper (I) Hypochlorite",
"CuClO2":"Copper (I) Chlorite",
"CuClO3":"Copper (I) Chlorate",
"CuClO4":"Copper (I) Perchlorate",
"CuBrO3":"Copper (I) Bromate",
"CuIO3":"Copper (I) Iodate",
"CuIO4":"Copper (I) Periodate",
"CuC2H3O2":"Copper (I) Acetate",
"CuH2PO4":"Copper (I) Dihydrogen Phosphate",
"Cu2CO3":"Copper (I) Carbonate",
"Cu2SO3":"Copper (I) Sulfite",
"Cu2SO4":"Copper (I) Sulfate",
"Cu2S2O3":"Copper (I) Thiosulfate",
"Cu2O2":"Copper (I) Peroxide",
"Cu2CrO4":"Copper (I) Chromate",
"Cu2Cr2O7":"Copper (I) Dichromate",
"Cu2HPO4":"Copper (I) Hydrogen Phosphate",
"Cu3PO4":"Copper (I) Phosphate",
"Cu3AsO4":"Copper (I) Arsenate",
"Cu3N":"Copper (I) Nitride",
"Cu3P":"Copper (I) Phosphide",
"Cu3As":"Copper (I) Arsenide",
"Cu2O":"Copper (I) Oxide",
"Cu2S":"Copper (I) Sulfide",
"Cu2Se":"Copper (I) Selenide",
"Cu2Te":"Copper (I) Telluride",
"CuF":"Copper (I) Fluoride",
"CuCl":"Copper (I) Chloride",
"CuBr":"Copper (I) Bromide",
"CuI":"Copper (I) Iodide",
"Cu(NO2)2":"Copper (II) Nitrite",
"Cu(NO3)2":"Copper (II) Nitrate",
"Cu(HSO4)2":"Copper (II) Hydrogen Sulfate",
"Cu(OH)2":"Copper (II) Hydroxide",
"Cu(CN)2":"Copper (II) Cyanide",
"Cu(MnO4)2":"Copper (II) Permanganate",
"Cu(HCO3)2":"Copper (II) Hydrogen Carbonate",
"Cu(ClO)2":"Copper (II) Hypochlorite",
"Cu(ClO2)2":"Copper (II) Chlorite",
"Cu(ClO3)2":"Copper (II) Chlorate",
"Cu(ClO4)2":"Copper (II) Perchlorate",
"Cu(BrO3)2":"Copper (II) Bromate",
"Cu(IO3)2":"Copper (II) Iodate",
"Cu(IO4)2":"Copper (II) Periodate",
"Cu(C2H3O2)2":"Copper (II) Acetate",
"Cu(H2PO4)2":"Copper (II) Dihydrogen Phosphate",
"CuCO3":"Copper (II) Carbonate",
"CuSO3":"Copper (II) Sulfite",
"CuSO4":"Copper (II) Sulfate",
"CuS2O3":"Copper (II) Thiosulfate",
"CuO2":"Copper (II) Peroxide",
"CuCrO4":"Copper (II) Chromate",
"CuCr2O7":"Copper (II) Dichromate",
"CuHPO4":"Copper (II) Hydrogen Phosphate",
"Cu3(PO4)2":"Copper (II) Phosphate",
"Cu3(AsO4)2":"Copper (II) Arsenate",
"Cu3N2":"Copper (II) Nitride",
"Cu3P2":"Copper (II) Phosphide",
"Cu3As2":"Copper (II) Arsenide",
"CuO":"Copper (II) Oxide",
"CuS":"Copper (II) Sulfide",
"CuSe":"Copper (II) Selenide",
"CuTe":"Copper (II) Telluride",
"CuF2":"Copper (II) Fluoride",
"CuCl2":"Copper (II) Chloride",
"CuBr2":"Copper (II) Bromide",
"CuI2":"Copper (II) Iodide",
"AgNO2":"Silver Nitrite",
"AgNO3":"Silver Nitrate",
"AgHSO4":"Silver Hydrogen Sulfate",
"AgOH":"Silver Hydroxide",
"AgCN":"Silver Cyanide",
"AgMnO4":"Silver Permanganate",
"AgHCO3":"Silver Hydrogen Carbonate",
"AgClO":"Silver Hypochlorite",
"AgClO2":"Silver Chlorite",
"AgClO3":"Silver Chlorate",
"AgClO4":"Silver Perchlorate",
"AgBrO3":"Silver Bromate",
"AgIO3":"Silver Iodate",
"AgIO4":"Silver Periodate",
"AgC2H3O2":"Silver Acetate",
"AgH2PO4":"Silver Dihydrogen Phosphate",
"Ag2CO3":"Silver Carbonate",
"Ag2SO3":"Silver Sulfite",
"Ag2SO4":"Silver Sulfate",
"Ag2S2O3":"Silver Thiosulfate",
"Ag2O2":"Silver Peroxide",
"Ag2CrO4":"Silver Chromate",
"Ag2Cr2O7":"Silver Dichromate",
"Ag2HPO4":"Silver Hydrogen Phosphate",
"Ag3PO4":"Silver Phosphate",
"Ag3AsO4":"Silver Arsenate",
"Ag3N":"Silver Nitride",
"Ag3P":"Silver Phosphide",
"Ag3As":"Silver Arsenide",
"Ag2O":"Silver Oxide",
"Ag2S":"Silver Sulfide",
"Ag2Se":"Silver Selenide",
"Ag2Te":"Silver Telluride",
"AgF":"Silver Fluoride",
"AgCl":"Silver Chloride",
"AgBr":"Silver Bromide",
"AgI":"Silver Iodide",
"AuNO2":"Gold (I) Nitrite",
"AuNO3":"Gold (I) Nitrate",
"AuHSO4":"Gold (I) Hydrogen Sulfate",
"AuOH":"Gold (I) Hydroxide",
"AuCN":"Gold (I) Cyanide",
"AuMnO4":"Gold (I) Permanganate",
"AuHCO3":"Gold (I) Hydrogen Carbonate",
"AuClO":"Gold (I) Hypochlorite",
"AuClO2":"Gold (I) Chlorite",
"AuClO3":"Gold (I) Chlorate",
"AuClO4":"Gold (I) Perchlorate",
"AuBrO3":"Gold (I) Bromate",
"AuIO3":"Gold (I) Iodate",
"AuIO4":"Gold (I) Periodate",
"AuC2H3O2":"Gold (I) Acetate",
"AuH2PO4":"Gold (I) Dihydrogen Phosphate",
"Au2CO3":"Gold (I) Carbonate",
"Au2SO3":"Gold (I) Sulfite",
"Au2SO4":"Gold (I) Sulfate",
"Au2S2O3":"Gold (I) Thiosulfate",
"Au2O2":"Gold (I) Peroxide",
"Au2CrO4":"Gold (I) Chromate",
"Au2Cr2O7":"Gold (I) Dichromate",
"Au2HPO4":"Gold (I) Hydrogen Phosphate",
"Au3PO4":"Gold (I) Phosphate",
"Au3AsO4":"Gold (I) Arsenate",
"Au3N":"Gold (I) Nitride",
"Au3P":"Gold (I) Phosphide",
"Au3As":"Gold (I) Arsenide",
"Au2O":"Gold (I) Oxide",
"Au2S":"Gold (I) Sulfide",
"Au2Se":"Gold (I) Selenide",
"Au2Te":"Gold (I) Telluride",
"AuF":"Gold (I) Fluoride",
"AuCl":"Gold (I) Chloride",
"AuBr":"Gold (I) Bromide",
"AuI":"Gold (I) Iodide",
"Au(NO2)3":"Gold (III) Nitrite",
"Au(NO3)3":"Gold (III) Nitrate",
"Au(HSO4)3":"Gold (III) Hydrogen Sulfate",
"Au(OH)3":"Gold (III) Hydroxide",
"Au(CN)3":"Gold (III) Cyanide",
"Au(MnO4)3":"Gold (III) Permanganate",
"Au(HCO3)3":"Gold (III) Hydrogen Carbonate",
"Au(ClO)3":"Gold (III) Hypochlorite",
"Au(ClO2)3":"Gold (III) Chlorite",
"Au(ClO3)3":"Gold (III) Chlorate",
"Au(ClO4)3":"Gold (III) Perchlorate",
"Au(BrO3)3":"Gold (III) Bromate",
"Au(IO3)3":"Gold (III) Iodate",
"Au(IO4)3":"Gold (III) Periodate",
"Au(C2H3O2)3":"Gold (III) Acetate",
"Au(H2PO4)3":"Gold (III) Dihydrogen Phosphate",
"Au2(CO3)3":"Gold (III) Carbonate",
"Au2(SO3)3":"Gold (III) Sulfite",
"Au2(SO4)3":"Gold (III) Sulfate",
"Au2(S2O3)3":"Gold (III) Thiosulfate",
"Au2(O2)3":"Gold (III) Peroxide",
"Au2(CrO4)3":"Gold (III) Chromate",
"Au2(Cr2O7)3":"Gold (III) Dichromate",
"Au2(HPO4)3":"Gold (III) Hydrogen Phosphate",
"AuPO4":"Gold (III) Phosphate",
"AuAsO4":"Gold (III) Arsenate",
"AuN":"Gold (III) Nitride",
"AuP":"Gold (III) Phosphide",
"AuAs":"Gold (III) Arsenide",
"Au2O3":"Gold (III) Oxide",
"Au2S3":"Gold (III) Sulfide",
"Au2Se3":"Gold (III) Selenide",
"Au2Te3":"Gold (III) Telluride",
"AuF3":"Gold (III) Fluoride",
"AuCl3":"Gold (III) Chloride",
"AuBr3":"Gold (III) Bromide",
"AuI3":"Gold (III) Iodide",
"Zn(NO2)2":"Zinc Nitrite",
"Zn(NO3)2":"Zinc Nitrate",
"Zn(HSO4)2":"Zinc Hydrogen Sulfate",
"Zn(OH)2":"Zinc Hydroxide",
"Zn(CN)2":"Zinc Cyanide",
"Zn(MnO4)2":"Zinc Permanganate",
"Zn(HCO3)2":"Zinc Hydrogen Carbonate",
"Zn(ClO)2":"Zinc Hypochlorite",
"Zn(ClO2)2":"Zinc Chlorite",
"Zn(ClO3)2":"Zinc Chlorate",
"Zn(ClO4)2":"Zinc Perchlorate",
"Zn(BrO3)2":"Zinc Bromate",
"Zn(IO3)2":"Zinc Iodate",
"Zn(IO4)2":"Zinc Periodate",
"Zn(C2H3O2)2":"Zinc Acetate",
"Zn(H2PO4)2":"Zinc Dihydrogen Phosphate",
"ZnCO3":"Zinc Carbonate",
"ZnSO3":"Zinc Sulfite",
"ZnSO4":"Zinc Sulfate",
"ZnS2O3":"Zinc Thiosulfate",
"ZnO2":"Zinc Peroxide",
"ZnCrO4":"Zinc Chromate",
"ZnCr2O7":"Zinc Dichromate",
"ZnHPO4":"Zinc Hydrogen Phosphate",
"Zn3(PO4)2":"Zinc Phosphate",
"Zn3(AsO4)2":"Zinc Arsenate",
"Zn3N2":"Zinc Nitride",
"Zn3P2":"Zinc Phosphide",
"Zn3As2":"Zinc Arsenide",
"ZnO":"Zinc Oxide",
"ZnS":"Zinc Sulfide",
"ZnSe":"Zinc Selenide",
"ZnTe":"Zinc Telluride",
"ZnF2":"Zinc Fluoride",
"ZnCl2":"Zinc Chloride",
"ZnBr2":"Zinc Bromide",
"ZnI2":"Zinc Iodide",
"Cd(NO2)2":"Cadmium Nitrite",
"Cd(NO3)2":"Cadmium Nitrate",
"Cd(HSO4)2":"Cadmium Hydrogen Sulfate",
"Cd(OH)2":"Cadmium Hydroxide",
"Cd(CN)2":"Cadmium Cyanide",
"Cd(MnO4)2":"Cadmium Permanganate",
"Cd(HCO3)2":"Cadmium Hydrogen Carbonate",
"Cd(ClO)2":"Cadmium Hypochlorite",
"Cd(ClO2)2":"Cadmium Chlorite",
"Cd(ClO3)2":"Cadmium Chlorate",
"Cd(ClO4)2":"Cadmium Perchlorate",
"Cd(BrO3)2":"Cadmium Bromate",
"Cd(IO3)2":"Cadmium Iodate",
"Cd(IO4)2":"Cadmium Periodate",
"Cd(C2H3O2)2":"Cadmium Acetate",
"Cd(H2PO4)2":"Cadmium Dihydrogen Phosphate",
"CdCO3":"Cadmium Carbonate",
"CdSO3":"Cadmium Sulfite",
"CdSO4":"Cadmium Sulfate",
"CdS2O3":"Cadmium Thiosulfate",
"CdO2":"Cadmium Peroxide",
"CdCrO4":"Cadmium Chromate",
"CdCr2O7":"Cadmium Dichromate",
"CdHPO4":"Cadmium Hydrogen Phosphate",
"Cd3(PO4)2":"Cadmium Phosphate",
"Cd3(AsO4)2":"Cadmium Arsenate",
"Cd3N2":"Cadmium Nitride",
"Cd3P2":"Cadmium Phosphide",
"Cd3As2":"Cadmium Arsenide",
"CdO":"Cadmium Oxide",
"CdS":"Cadmium Sulfide",
"CdSe":"Cadmium Selenide",
"CdTe":"Cadmium Telluride",
"CdF2":"Cadmium Fluoride",
"CdCl2":"Cadmium Chloride",
"CdBr2":"Cadmium Bromide",
"CdI2":"Cadmium Iodide",
"Hg2(NO2)2":"Mercury (I) Nitrite",
"Hg2(NO3)2":"Mercury (I) Nitrate",
"Hg2(HSO4)2":"Mercury (I) Hydrogen Sulfate",
"Hg2(OH)2":"Mercury (I) Hydroxide",
"Hg2(CN)2":"Mercury (I) Cyanide",
"Hg2(MnO4)2":"Mercury (I) Permanganate",
"Hg2(HCO3)2":"Mercury (I) Hydrogen Carbonate",
"Hg2(ClO)2":"Mercury (I) Hypochlorite",
"Hg2(ClO2)2":"Mercury (I) Chlorite",
"Hg2(ClO3)2":"Mercury (I) Chlorate",
"Hg2(ClO4)2":"Mercury (I) Perchlorate",
"Hg2(BrO3)2":"Mercury (I) Bromate",
"Hg2(IO3)2":"Mercury (I) Iodate",
"Hg2(IO4)2":"Mercury (I) Periodate",
"Hg2(C2H3O2)2":"Mercury (I) Acetate",
"Hg2(H2PO4)2":"Mercury (I) Dihydrogen Phosphate",
"Hg2CO3":"Mercury (I) Carbonate",
"Hg2SO3":"Mercury (I) Sulfite",
"Hg2SO4":"Mercury (I) Sulfate",
"Hg2S2O3":"Mercury (I) Thiosulfate",
"Hg2O2":"Mercury (I) Peroxide",
"Hg2CrO4":"Mercury (I) Chromate",
"Hg2Cr2O7":"Mercury (I) Dichromate",
"Hg2HPO4":"Mercury (I) Hydrogen Phosphate",
"(Hg2)3(PO4)2":"Mercury (I) Phosphate",
"(Hg2)3(AsO4)2":"Mercury (I) Arsenate",
"(Hg2)3N2":"Mercury (I) Nitride",
"(Hg2)3P2":"Mercury (I) Phosphide",
"(Hg2)3As2":"Mercury (I) Arsenide",
"Hg2O":"Mercury (I) Oxide",
"Hg2S":"Mercury (I) Sulfide",
"Hg2Se":"Mercury (I) Selenide",
"Hg2Te":"Mercury (I) Telluride",
"Hg2F2":"Mercury (I) Fluoride",
"Hg2Cl2":"Mercury (I) Chloride",
"Hg2Br2":"Mercury (I) Bromide",
"Hg2I2":"Mercury (I) Iodide",
"Hg(NO2)2":"Mercury (II) Nitrite",
"Hg(NO3)2":"Mercury (II) Nitrate",
"Hg(HSO4)2":"Mercury (II) Hydrogen Sulfate",
"Hg(OH)2":"Mercury (II) Hydroxide",
"Hg(CN)2":"Mercury (II) Cyanide",
"Hg(MnO4)2":"Mercury (II) Permanganate",
"Hg(HCO3)2":"Mercury (II) Hydrogen Carbonate",
"Hg(ClO)2":"Mercury (II) Hypochlorite",
"Hg(ClO2)2":"Mercury (II) Chlorite",
"Hg(ClO3)2":"Mercury (II) Chlorate",
"Hg(ClO4)2":"Mercury (II) Perchlorate",
"Hg(BrO3)2":"Mercury (II) Bromate",
"Hg(IO3)2":"Mercury (II) Iodate",
"Hg(IO4)2":"Mercury (II) Periodate",
"Hg(C2H3O2)2":"Mercury (II) Acetate",
"Hg(H2PO4)2":"Mercury (II) Dihydrogen Phosphate",
"HgCO3":"Mercury (II) Carbonate",
"HgSO3":"Mercury (II) Sulfite",
"HgSO4":"Mercury (II) Sulfate",
"HgS2O3":"Mercury (II) Thiosulfate",
"HgO2":"Mercury (II) Peroxide",
"HgCrO4":"Mercury (II) Chromate",
"HgCr2O7":"Mercury (II) Dichromate",
"HgHPO4":"Mercury (II) Hydrogen Phosphate",
"Hg3(PO4)2":"Mercury (II) Phosphate",
"Hg3(AsO4)2":"Mercury (II) Arsenate",
"Hg3N2":"Mercury (II) Nitride",
"Hg3P2":"Mercury (II) Phosphide",
"Hg3As2":"Mercury (II) Arsenide",
"HgO":"Mercury (II) Oxide",
"HgS":"Mercury (II) Sulfide",
"HgSe":"Mercury (II) Selenide",
"HgTe":"Mercury (II) Telluride",
"HgF2":"Mercury (II) Fluoride",
"HgCl2":"Mercury (II) Chloride",
"HgBr2":"Mercury (II) Bromide",
"HgI2":"Mercury (II) Iodide",
"Al(NO2)3":"Aluminum Nitrite",
"Al(NO3)3":"Aluminum Nitrate",
"Al(HSO4)3":"Aluminum Hydrogen Sulfate",
"Al(OH)3":"Aluminum Hydroxide",
"Al(CN)3":"Aluminum Cyanide",
"Al(MnO4)3":"Aluminum Permanganate",
"Al(HCO3)3":"Aluminum Hydrogen Carbonate",
"Al(ClO)3":"Aluminum Hypochlorite",
"Al(ClO2)3":"Aluminum Chlorite",
"Al(ClO3)3":"Aluminum Chlorate",
"Al(ClO4)3":"Aluminum Perchlorate",
"Al(BrO3)3":"Aluminum Bromate",
"Al(IO3)3":"Aluminum Iodate",
"Al(IO4)3":"Aluminum Periodate",
"Al(C2H3O2)3":"Aluminum Acetate",
"Al(H2PO4)3":"Aluminum Dihydrogen Phosphate",
"Al2(CO3)3":"Aluminum Carbonate",
"Al2(SO3)3":"Aluminum Sulfite",
"Al2(SO4)3":"Aluminum Sulfate",
"Al2(S2O3)3":"Aluminum Thiosulfate",
"Al2(O2)3":"Aluminum Peroxide",
"Al2(CrO4)3":"Aluminum Chromate",
"Al2(Cr2O7)3":"Aluminum Dichromate",
"Al2(HPO4)3":"Aluminum Hydrogen Phosphate",
"AlPO4":"Aluminum Phosphate",
"AlAsO4":"Aluminum Arsenate",
"AlN":"Aluminum Nitride",
"AlP":"Aluminum Phosphide",
"AlAs":"Aluminum Arsenide",
"Al2O3":"Aluminum Oxide",
"Al2S3":"Aluminum Sulfide",
"Al2Se3":"Aluminum Selenide",
"Al2Te3":"Aluminum Telluride",
"AlF3":"Aluminum Fluoride",
"AlCl3":"Aluminum Chloride",
"AlBr3":"Aluminum Bromide",
"AlI3":"Aluminum Iodide",
"Ga(NO2)2":"Gallium (II) Nitrite",
"Ga(NO3)2":"Gallium (II) Nitrate",
"Ga(HSO4)2":"Gallium (II) Hydrogen Sulfate",
"Ga(OH)2":"Gallium (II) Hydroxide",
"Ga(CN)2":"Gallium (II) Cyanide",
"Ga(MnO4)2":"Gallium (II) Permanganate",
"Ga(HCO3)2":"Gallium (II) Hydrogen Carbonate",
"Ga(ClO)2":"Gallium (II) Hypochlorite",
"Ga(ClO2)2":"Gallium (II) Chlorite",
"Ga(ClO3)2":"Gallium (II) Chlorate",
"Ga(ClO4)2":"Gallium (II) Perchlorate",
"Ga(BrO3)2":"Gallium (II) Bromate",
"Ga(IO3)2":"Gallium (II) Iodate",
"Ga(IO4)2":"Gallium (II) Periodate",
"Ga(C2H3O2)2":"Gallium (II) Acetate",
"Ga(H2PO4)2":"Gallium (II) Dihydrogen Phosphate",
"GaCO3":"Gallium (II) Carbonate",
"GaSO3":"Gallium (II) Sulfite",
"GaSO4":"Gallium (II) Sulfate",
"GaS2O3":"Gallium (II) Thiosulfate",
"GaO2":"Gallium (II) Peroxide",
"GaCrO4":"Gallium (II) Chromate",
"GaCr2O7":"Gallium (II) Dichromate",
"GaHPO4":"Gallium (II) Hydrogen Phosphate",
"Ga3(PO4)2":"Gallium (II) Phosphate",
"Ga3(AsO4)2":"Gallium (II) Arsenate",
"Ga3N2":"Gallium (II) Nitride",
"Ga3P2":"Gallium (II) Phosphide",
"Ga3As2":"Gallium (II) Arsenide",
"GaO":"Gallium (II) Oxide",
"GaS":"Gallium (II) Sulfide",
"GaSe":"Gallium (II) Selenide",
"GaTe":"Gallium (II) Telluride",
"GaF2":"Gallium (II) Fluoride",
"GaCl2":"Gallium (II) Chloride",
"GaBr2":"Gallium (II) Bromide",
"GaI2":"Gallium (II) Iodide",
"Ga(NO2)3":"Gallium (III) Nitrite",
"Ga(NO3)3":"Gallium (III) Nitrate",
"Ga(HSO4)3":"Gallium (III) Hydrogen Sulfate",
"Ga(OH)3":"Gallium (III) Hydroxide",
"Ga(CN)3":"Gallium (III) Cyanide",
"Ga(MnO4)3":"Gallium (III) Permanganate",
"Ga(HCO3)3":"Gallium (III) Hydrogen Carbonate",
"Ga(ClO)3":"Gallium (III) Hypochlorite",
"Ga(ClO2)3":"Gallium (III) Chlorite",
"Ga(ClO3)3":"Gallium (III) Chlorate",
"Ga(ClO4)3":"Gallium (III) Perchlorate",
"Ga(BrO3)3":"Gallium (III) Bromate",
"Ga(IO3)3":"Gallium (III) Iodate",
"Ga(IO4)3":"Gallium (III) Periodate",
"Ga(C2H3O2)3":"Gallium (III) Acetate",
"Ga(H2PO4)3":"Gallium (III) Dihydrogen Phosphate",
"Ga2(CO3)3":"Gallium (III) Carbonate",
"Ga2(SO3)3":"Gallium (III) Sulfite",
"Ga2(SO4)3":"Gallium (III) Sulfate",
"Ga2(S2O3)3":"Gallium (III) Thiosulfate",
"Ga2(O2)3":"Gallium (III) Peroxide",
"Ga2(CrO4)3":"Gallium (III) Chromate",
"Ga2(Cr2O7)3":"Gallium (III) Dichromate",
"Ga2(HPO4)3":"Gallium (III) Hydrogen Phosphate",
"GaPO4":"Gallium (III) Phosphate",
"GaAsO4":"Gallium (III) Arsenate",
"GaN":"Gallium (III) Nitride",
"GaP":"Gallium (III) Phosphide",
"GaAs":"Gallium (III) Arsenide",
"Ga2O3":"Gallium (III) Oxide",
"Ga2S3":"Gallium (III) Sulfide",
"Ga2Se3":"Gallium (III) Selenide",
"Ga2Te3":"Gallium (III) Telluride",
"GaF3":"Gallium (III) Fluoride",
"GaCl3":"Gallium (III) Chloride",
"GaBr3":"Gallium (III) Bromide",
"GaI3":"Gallium (III) Iodide",
"InNO2":"Indium (I) Nitrite",
"InNO3":"Indium (I) Nitrate",
"InHSO4":"Indium (I) Hydrogen Sulfate",
"InOH":"Indium (I) Hydroxide",
"InCN":"Indium (I) Cyanide",
"InMnO4":"Indium (I) Permanganate",
"InHCO3":"Indium (I) Hydrogen Carbonate",
"InClO":"Indium (I) Hypochlorite",
"InClO2":"Indium (I) Chlorite",
"InClO3":"Indium (I) Chlorate",
"InClO4":"Indium (I) Perchlorate",
"InBrO3":"Indium (I) Bromate",
"InIO3":"Indium (I) Iodate",
"InIO4":"Indium (I) Periodate",
"InC2H3O2":"Indium (I) Acetate",
"InH2PO4":"Indium (I) Dihydrogen Phosphate",
"In2CO3":"Indium (I) Carbonate",
"In2SO3":"Indium (I) Sulfite",
"In2SO4":"Indium (I) Sulfate",
"In2S2O3":"Indium (I) Thiosulfate",
"In2O2":"Indium (I) Peroxide",
"In2CrO4":"Indium (I) Chromate",
"In2Cr2O7":"Indium (I) Dichromate",
"In2HPO4":"Indium (I) Hydrogen Phosphate",
"In3PO4":"Indium (I) Phosphate",
"In3AsO4":"Indium (I) Arsenate",
"In3N":"Indium (I) Nitride",
"In3P":"Indium (I) Phosphide",
"In3As":"Indium (I) Arsenide",
"In2O":"Indium (I) Oxide",
"In2S":"Indium (I) Sulfide",
"In2Se":"Indium (I) Selenide",
"In2Te":"Indium (I) Telluride",
"InF":"Indium (I) Fluoride",
"InCl":"Indium (I) Chloride",
"InBr":"Indium (I) Bromide",
"InI":"Indium (I) Iodide",
"In(NO2)2":"Indium (II) Nitrite",
"In(NO3)2":"Indium (II) Nitrate",
"In(HSO4)2":"Indium (II) Hydrogen Sulfate",
"In(OH)2":"Indium (II) Hydroxide",
"In(CN)2":"Indium (II) Cyanide",
"In(MnO4)2":"Indium (II) Permanganate",
"In(HCO3)2":"Indium (II) Hydrogen Carbonate",
"In(ClO)2":"Indium (II) Hypochlorite",
"In(ClO2)2":"Indium (II) Chlorite",
"In(ClO3)2":"Indium (II) Chlorate",
"In(ClO4)2":"Indium (II) Perchlorate",
"In(BrO3)2":"Indium (II) Bromate",
"In(IO3)2":"Indium (II) Iodate",
"In(IO4)2":"Indium (II) Periodate",
"In(C2H3O2)2":"Indium (II) Acetate",
"In(H2PO4)2":"Indium (II) Dihydrogen Phosphate",
"InCO3":"Indium (II) Carbonate",
"InSO3":"Indium (II) Sulfite",
"InSO4":"Indium (II) Sulfate",
"InS2O3":"Indium (II) Thiosulfate",
"InO2":"Indium (II) Peroxide",
"InCrO4":"Indium (II) Chromate",
"InCr2O7":"Indium (II) Dichromate",
"InHPO4":"Indium (II) Hydrogen Phosphate",
"In3(PO4)2":"Indium (II) Phosphate",
"In3(AsO4)2":"Indium (II) Arsenate",
"In3N2":"Indium (II) Nitride",
"In3P2":"Indium (II) Phosphide",
"In3As2":"Indium (II) Arsenide",
"InO":"Indium (II) Oxide",
"InS":"Indium (II) Sulfide",
"InSe":"Indium (II) Selenide",
"InTe":"Indium (II) Telluride",
"InF2":"Indium (II) Fluoride",
"InCl2":"Indium (II) Chloride",
"InBr2":"Indium (II) Bromide",
"InI2":"Indium (II) Iodide",
"In(NO2)3":"Indium (III) Nitrite",
"In(NO3)3":"Indium (III) Nitrate",
"In(HSO4)3":"Indium (III) Hydrogen Sulfate",
"In(OH)3":"Indium (III) Hydroxide",
"In(CN)3":"Indium (III) Cyanide",
"In(MnO4)3":"Indium (III) Permanganate",
"In(HCO3)3":"Indium (III) Hydrogen Carbonate",
"In(ClO)3":"Indium (III) Hypochlorite",
"In(ClO2)3":"Indium (III) Chlorite",
"In(ClO3)3":"Indium (III) Chlorate",
"In(ClO4)3":"Indium (III) Perchlorate",
"In(BrO3)3":"Indium (III) Bromate",
"In(IO3)3":"Indium (III) Iodate",
"In(IO4)3":"Indium (III) Periodate",
"In(C2H3O2)3":"Indium (III) Acetate",
"In(H2PO4)3":"Indium (III) Dihydrogen Phosphate",
"In2(CO3)3":"Indium (III) Carbonate",
"In2(SO3)3":"Indium (III) Sulfite",
"In2(SO4)3":"Indium (III) Sulfate",
"In2(S2O3)3":"Indium (III) Thiosulfate",
"In2(O2)3":"Indium (III) Peroxide",
"In2(CrO4)3":"Indium (III) Chromate",
"In2(Cr2O7)3":"Indium (III) Dichromate",
"In2(HPO4)3":"Indium (III) Hydrogen Phosphate",
"InPO4":"Indium (III) Phosphate",
"InAsO4":"Indium (III) Arsenate",
"InN":"Indium (III) Nitride",
"InP":"Indium (III) Phosphide",
"InAs":"Indium (III) Arsenide",
"In2O3":"Indium (III) Oxide",
"In2S3":"Indium (III) Sulfide",
"In2Se3":"Indium (III) Selenide",
"In2Te3":"Indium (III) Telluride",
"InF3":"Indium (III) Fluoride",
"InCl3":"Indium (III) Chloride",
"InBr3":"Indium (III) Bromide",
"InI3":"Indium (III) Iodide",
"TlNO2":"Thallium (I) Nitrite",
"TlNO3":"Thallium (I) Nitrate",
"TlHSO4":"Thallium (I) Hydrogen Sulfate",
"TlOH":"Thallium (I) Hydroxide",
"TlCN":"Thallium (I) Cyanide",
"TlMnO4":"Thallium (I) Permanganate",
"TlHCO3":"Thallium (I) Hydrogen Carbonate",
"TlClO":"Thallium (I) Hypochlorite",
"TlClO2":"Thallium (I) Chlorite",
"TlClO3":"Thallium (I) Chlorate",
"TlClO4":"Thallium (I) Perchlorate",
"TlBrO3":"Thallium (I) Bromate",
"TlIO3":"Thallium (I) Iodate",
"TlIO4":"Thallium (I) Periodate",
"TlC2H3O2":"Thallium (I) Acetate",
"TlH2PO4":"Thallium (I) Dihydrogen Phosphate",
"Tl2CO3":"Thallium (I) Carbonate",
"Tl2SO3":"Thallium (I) Sulfite",
"Tl2SO4":"Thallium (I) Sulfate",
"Tl2S2O3":"Thallium (I) Thiosulfate",
"Tl2O2":"Thallium (I) Peroxide",
"Tl2CrO4":"Thallium (I) Chromate",
"Tl2Cr2O7":"Thallium (I) Dichromate",
"Tl2HPO4":"Thallium (I) Hydrogen Phosphate",
"Tl3PO4":"Thallium (I) Phosphate",
"Tl3AsO4":"Thallium (I) Arsenate",
"Tl3N":"Thallium (I) Nitride",
"Tl3P":"Thallium (I) Phosphide",
"Tl3As":"Thallium (I) Arsenide",
"Tl2O":"Thallium (I) Oxide",
"Tl2S":"Thallium (I) Sulfide",
"Tl2Se":"Thallium (I) Selenide",
"Tl2Te":"Thallium (I) Telluride",
"TlF":"Thallium (I) Fluoride",
"TlCl":"Thallium (I) Chloride",
"TlBr":"Thallium (I) Bromide",
"TlI":"Thallium (I) Iodide",
"Tl(NO2)3":"Thallium (III) Nitrite",
"Tl(NO3)3":"Thallium (III) Nitrate",
"Tl(HSO4)3":"Thallium (III) Hydrogen Sulfate",
"Tl(OH)3":"Thallium (III) Hydroxide",
"Tl(CN)3":"Thallium (III) Cyanide",
"Tl(MnO4)3":"Thallium (III) Permanganate",
"Tl(HCO3)3":"Thallium (III) Hydrogen Carbonate",
"Tl(ClO)3":"Thallium (III) Hypochlorite",
"Tl(ClO2)3":"Thallium (III) Chlorite",
"Tl(ClO3)3":"Thallium (III) Chlorate",
"Tl(ClO4)3":"Thallium (III) Perchlorate",
"Tl(BrO3)3":"Thallium (III) Bromate",
"Tl(IO3)3":"Thallium (III) Iodate",
"Tl(IO4)3":"Thallium (III) Periodate",
"Tl(C2H3O2)3":"Thallium (III) Acetate",
"Tl(H2PO4)3":"Thallium (III) Dihydrogen Phosphate",
"Tl2(CO3)3":"Thallium (III) Carbonate",
"Tl2(SO3)3":"Thallium (III) Sulfite",
"Tl2(SO4)3":"Thallium (III) Sulfate",
"Tl2(S2O3)3":"Thallium (III) Thiosulfate",
"Tl2(O2)3":"Thallium (III) Peroxide",
"Tl2(CrO4)3":"Thallium (III) Chromate",
"Tl2(Cr2O7)3":"Thallium (III) Dichromate",
"Tl2(HPO4)3":"Thallium (III) Hydrogen Phosphate",
"TlPO4":"Thallium (III) Phosphate",
"TlAsO4":"Thallium (III) Arsenate",
"TlN":"Thallium (III) Nitride",
"TlP":"Thallium (III) Phosphide",
"TlAs":"Thallium (III) Arsenide",
"Tl2O3":"Thallium (III) Oxide",
"Tl2S3":"Thallium (III) Sulfide",
"Tl2Se3":"Thallium (III) Selenide",
"Tl2Te3":"Thallium (III) Telluride",
"TlF3":"Thallium (III) Fluoride",
"TlCl3":"Thallium (III) Chloride",
"TlBr3":"Thallium (III) Bromide",
"TlI3":"Thallium (III) Iodide",
"Sn(NO2)2":"Tin (II) Nitrite",
"Sn(NO3)2":"Tin (II) Nitrate",
"Sn(HSO4)2":"Tin (II) Hydrogen Sulfate",
"Sn(OH)2":"Tin (II) Hydroxide",
"Sn(CN)2":"Tin (II) Cyanide",
"Sn(MnO4)2":"Tin (II) Permanganate",
"Sn(HCO3)2":"Tin (II) Hydrogen Carbonate",
"Sn(ClO)2":"Tin (II) Hypochlorite",
"Sn(ClO2)2":"Tin (II) Chlorite",
"Sn(ClO3)2":"Tin (II) Chlorate",
"Sn(ClO4)2":"Tin (II) Perchlorate",
"Sn(BrO3)2":"Tin (II) Bromate",
"Sn(IO3)2":"Tin (II) Iodate",
"Sn(IO4)2":"Tin (II) Periodate",
"Sn(C2H3O2)2":"Tin (II) Acetate",
"Sn(H2PO4)2":"Tin (II) Dihydrogen Phosphate",
"SnCO3":"Tin (II) Carbonate",
"SnSO3":"Tin (II) Sulfite",
"SnSO4":"Tin (II) Sulfate",
"SnS2O3":"Tin (II) Thiosulfate",
"SnO2":"Tin (II) Peroxide",
"SnCrO4":"Tin (II) Chromate",
"SnCr2O7":"Tin (II) Dichromate",
"SnHPO4":"Tin (II) Hydrogen Phosphate",
"Sn3(PO4)2":"Tin (II) Phosphate",
"Sn3(AsO4)2":"Tin (II) Arsenate",
"Sn3N2":"Tin (II) Nitride",
"Sn3P2":"Tin (II) Phosphide",
"Sn3As2":"Tin (II) Arsenide",
"SnO":"Tin (II) Oxide",
"SnS":"Tin (II) Sulfide",
"SnSe":"Tin (II) Selenide",
"SnTe":"Tin (II) Telluride",
"SnF2":"Tin (II) Fluoride",
"SnCl2":"Tin (II) Chloride",
"SnBr2":"Tin (II) Bromide",
"SnI2":"Tin (II) Iodide",
"Sn(NO2)4":"Tin (IV) Nitrite",
"Sn(NO3)4":"Tin (IV) Nitrate",
"Sn(HSO4)4":"Tin (IV) Hydrogen Sulfate",
"Sn(OH)4":"Tin (IV) Hydroxide",
"Sn(CN)4":"Tin (IV) Cyanide",
"Sn(MnO4)4":"Tin (IV) Permanganate",
"Sn(HCO3)4":"Tin (IV) Hydrogen Carbonate",
"Sn(ClO)4":"Tin (IV) Hypochlorite",
"Sn(ClO2)4":"Tin (IV) Chlorite",
"Sn(ClO3)4":"Tin (IV) Chlorate",
"Sn(ClO4)4":"Tin (IV) Perchlorate",
"Sn(BrO3)4":"Tin (IV) Bromate",
"Sn(IO3)4":"Tin (IV) Iodate",
"Sn(IO4)4":"Tin (IV) Periodate",
"Sn(C2H3O2)4":"Tin (IV) Acetate",
"Sn(H2PO4)4":"Tin (IV) Dihydrogen Phosphate",
"Sn(CO3)2":"Tin (IV) Carbonate",
"Sn(SO3)2":"Tin (IV) Sulfite",
"Sn(SO4)2":"Tin (IV) Sulfate",
"Sn(S2O3)2":"Tin (IV) Thiosulfate",
"Sn(O2)2":"Tin (IV) Peroxide",
"Sn(CrO4)2":"Tin (IV) Chromate",
"Sn(Cr2O7)2":"Tin (IV) Dichromate",
"Sn(HPO4)2":"Tin (IV) Hydrogen Phosphate",
"Sn3(PO4)4":"Tin (IV) Phosphate",
"Sn3(AsO4)4":"Tin (IV) Arsenate",
"Sn3N4":"Tin (IV) Nitride",
"Sn3P4":"Tin (IV) Phosphide",
"Sn3As4":"Tin (IV) Arsenide",
"SnO2":"Tin (IV) Oxide",
"SnS2":"Tin (IV) Sulfide",
"SnSe2":"Tin (IV) Selenide",
"SnTe2":"Tin (IV) Telluride",
"SnF4":"Tin (IV) Fluoride",
"SnCl4":"Tin (IV) Chloride",
"SnBr4":"Tin (IV) Bromide",
"SnI4":"Tin (IV) Iodide",
"Pb(NO2)2":"Lead (II) Nitrite",
"Pb(NO3)2":"Lead (II) Nitrate",
"Pb(HSO4)2":"Lead (II) Hydrogen Sulfate",
"Pb(OH)2":"Lead (II) Hydroxide",
"Pb(CN)2":"Lead (II) Cyanide",
"Pb(MnO4)2":"Lead (II) Permanganate",
"Pb(HCO3)2":"Lead (II) Hydrogen Carbonate",
"Pb(ClO)2":"Lead (II) Hypochlorite",
"Pb(ClO2)2":"Lead (II) Chlorite",
"Pb(ClO3)2":"Lead (II) Chlorate",
"Pb(ClO4)2":"Lead (II) Perchlorate",
"Pb(BrO3)2":"Lead (II) Bromate",
"Pb(IO3)2":"Lead (II) Iodate",
"Pb(IO4)2":"Lead (II) Periodate",
"Pb(C2H3O2)2":"Lead (II) Acetate",
"Pb(H2PO4)2":"Lead (II) Dihydrogen Phosphate",
"PbCO3":"Lead (II) Carbonate",
"PbSO3":"Lead (II) Sulfite",
"PbSO4":"Lead (II) Sulfate",
"PbS2O3":"Lead (II) Thiosulfate",
"PbO2":"Lead (II) Peroxide",
"PbCrO4":"Lead (II) Chromate",
"PbCr2O7":"Lead (II) Dichromate",
"PbHPO4":"Lead (II) Hydrogen Phosphate",
"Pb3(PO4)2":"Lead (II) Phosphate",
"Pb3(AsO4)2":"Lead (II) Arsenate",
"Pb3N2":"Lead (II) Nitride",
"Pb3P2":"Lead (II) Phosphide",
"Pb3As2":"Lead (II) Arsenide",
"PbO":"Lead (II) Oxide",
"PbS":"Lead (II) Sulfide",
"PbSe":"Lead (II) Selenide",
"PbTe":"Lead (II) Telluride",
"PbF2":"Lead (II) Fluoride",
"PbCl2":"Lead (II) Chloride",
"PbBr2":"Lead (II) Bromide",
"PbI2":"Lead (II) Iodide",
"Pb(NO2)4":"Lead (IV) Nitrite",
"Pb(NO3)4":"Lead (IV) Nitrate",
"Pb(HSO4)4":"Lead (IV) Hydrogen Sulfate",
"Pb(OH)4":"Lead (IV) Hydroxide",
"Pb(CN)4":"Lead (IV) Cyanide",
"Pb(MnO4)4":"Lead (IV) Permanganate",
"Pb(HCO3)4":"Lead (IV) Hydrogen Carbonate",
"Pb(ClO)4":"Lead (IV) Hypochlorite",
"Pb(ClO2)4":"Lead (IV) Chlorite",
"Pb(ClO3)4":"Lead (IV) Chlorate",
"Pb(ClO4)4":"Lead (IV) Perchlorate",
"Pb(BrO3)4":"Lead (IV) Bromate",
"Pb(IO3)4":"Lead (IV) Iodate",
"Pb(IO4)4":"Lead (IV) Periodate",
"Pb(C2H3O2)4":"Lead (IV) Acetate",
"Pb(H2PO4)4":"Lead (IV) Dihydrogen Phosphate",
"Pb(CO3)2":"Lead (IV) Carbonate",
"Pb(SO3)2":"Lead (IV) Sulfite",
"Pb(SO4)2":"Lead (IV) Sulfate",
"Pb(S2O3)2":"Lead (IV) Thiosulfate",
"Pb(O2)2":"Lead (IV) Peroxide",
"Pb(CrO4)2":"Lead (IV) Chromate",
"Pb(Cr2O7)2":"Lead (IV) Dichromate",
"Pb(HPO4)2":"Lead (IV) Hydrogen Phosphate",
"Pb3(PO4)4":"Lead (IV) Phosphate",
"Pb3(AsO4)4":"Lead (IV) Arsenate",
"Pb3N4":"Lead (IV) Nitride",
"Pb3P4":"Lead (IV) Phosphide",
"Pb3As4":"Lead (IV) Arsenide",
"PbO2":"Lead (IV) Oxide",
"PbS2":"Lead (IV) Sulfide",
"PbSe2":"Lead (IV) Selenide",
"PbTe2":"Lead (IV) Telluride",
"PbF4":"Lead (IV) Fluoride",
"PbCl4":"Lead (IV) Chloride",
"PbBr4":"Lead (IV) Bromide",
"PbI4":"Lead (IV) Iodide",
"NH4NO2":"Ammonium Nitrite",
"NH4NO3":"Ammonium Nitrate",
"NH4HSO4":"Ammonium Hydrogen Sulfate",
"NH4OH":"Ammonium Hydroxide",
"NH4CN":"Ammonium Cyanide",
"NH4MnO4":"Ammonium Permanganate",
"NH4HCO3":"Ammonium Hydrogen Carbonate",
"NH4ClO":"Ammonium Hypochlorite",
"NH4ClO2":"Ammonium Chlorite",
"NH4ClO3":"Ammonium Chlorate",
"NH4ClO4":"Ammonium Perchlorate",
"NH4BrO3":"Ammonium Bromate",
"NH4IO3":"Ammonium Iodate",
"NH4IO4":"Ammonium Periodate",
"NH4C2H3O2":"Ammonium Acetate",
"NH4H2PO4":"Ammonium Dihydrogen Phosphate",
"(NH4)2CO3":"Ammonium Carbonate",
"(NH4)2SO3":"Ammonium Sulfite",
"(NH4)2SO4":"Ammonium Sulfate",
"(NH4)2S2O3":"Ammonium Thiosulfate",
"(NH4)2O2":"Ammonium Peroxide",
"(NH4)2CrO4":"Ammonium Chromate",
"(NH4)2Cr2O7":"Ammonium Dichromate",
"(NH4)2HPO4":"Ammonium Hydrogen Phosphate",
"(NH4)3PO4":"Ammonium Phosphate",
"(NH4)3AsO4":"Ammonium Arsenate",
"(NH4)3N":"Ammonium Nitride",
"(NH4)3P":"Ammonium Phosphide",
"(NH4)3As":"Ammonium Arsenide",
"(NH4)2O":"Ammonium Oxide",
"(NH4)2S":"Ammonium Sulfide",
"(NH4)2Se":"Ammonium Selenide",
"(NH4)2Te":"Ammonium Telluride",
"NH4F":"Ammonium Fluoride",
"NH4Cl":"Ammonium Chloride",
"NH4Br":"Ammonium Bromide",
"NH4":"Ammonium Iodide",
}